(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 640,
	height: 305,
	fps: 30,
	color: "#FFFFFF",
	manifest: [
		{src:"images/arrow.png", id:"arrow"},
		{src:"images/back_lag.png", id:"back_lag"},
		{src:"images/body.png", id:"body"},
		{src:"images/bow.png", id:"bow"},
		{src:"images/counter.png", id:"counter"},
		{src:"images/front_leg.png", id:"front_leg"},
		{src:"images/gora.png", id:"gora"},
		{src:"images/ground.png", id:"ground"},
		{src:"images/head.png", id:"head"},
		{src:"images/pric.png", id:"pric"},
		{src:"images/pric2.png", id:"pric2"},
		{src:"images/sand.png", id:"sand"},
		{src:"images/shield.png", id:"shield"},
		{src:"images/sky.png", id:"sky"},
		{src:"images/spear.png", id:"spear"},
		{src:"images/title.png", id:"title"}
	]
};



// symbols:



(lib.arrow = function() {
	this.initialize(img.arrow);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,45,50);


(lib.back_lag = function() {
	this.initialize(img.back_lag);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,112,74);


(lib.body = function() {
	this.initialize(img.body);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,80,98);


(lib.bow = function() {
	this.initialize(img.bow);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,92,237);


(lib.counter = function() {
	this.initialize(img.counter);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,109,65);


(lib.front_leg = function() {
	this.initialize(img.front_leg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,107,113);


(lib.gora = function() {
	this.initialize(img.gora);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,446,153);


(lib.ground = function() {
	this.initialize(img.ground);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,643,90);


(lib.head = function() {
	this.initialize(img.head);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,120,114);


(lib.pric = function() {
	this.initialize(img.pric);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,102,103);


(lib.pric2 = function() {
	this.initialize(img.pric2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,32,32);


(lib.sand = function() {
	this.initialize(img.sand);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,641,90);


(lib.shield = function() {
	this.initialize(img.shield);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,85,104);


(lib.sky = function() {
	this.initialize(img.sky);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,641,219);


(lib.spear = function() {
	this.initialize(img.spear);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,291,92);


(lib.title = function() {
	this.initialize(img.title);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,324,34);


(lib.Символ40 = function() {
	this.initialize();

	// Слой 3
	this.instance = new lib.title();
	this.instance.setTransform(-162.2,-16);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-162.2,-16,324,34);


(lib.Символ38 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.arrow();
	this.instance.setTransform(-22.5,-25);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-22.5,-25,45,50);


(lib.Символ27 = function() {
	this.initialize();

	// Слой 1 - копия
	this.instance = new lib.pric2();
	this.instance.setTransform(-16,-16);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-16,-16,32,32);


(lib.Символ24 = function() {
	this.initialize();

	// Слой 1 - копия
	this.instance = new lib.gora();
	this.instance.setTransform(-138.3,-82.2);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-138.3,-82.2,446,153);


(lib.Символ21 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.sand();
	this.instance.setTransform(-320.5,-45.2);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-320.5,-45.2,641,90);


(lib.Символ11 = function() {
	this.initialize();

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("ArhA4QkzgYABggQgBgfEzgYQEygYGvAAQGwAAEyAYQEzAYgBAfQABAgkzAYQkyAYmwAAQmvAAkygYg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-104.5,-8,209,16);


(lib.Символ7 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.back_lag();
	this.instance.setTransform(-56,-37);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-56,-37,112,74);


(lib.Символ6 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.spear();
	this.instance.setTransform(-145.5,-46);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-145.5,-46,291,92);


(lib.Символ5 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.shield();
	this.instance.setTransform(-42.5,-52);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-42.5,-52,85,104);


(lib.Символ4 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.front_leg();
	this.instance.setTransform(-53.5,-56.5);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-53.5,-56.5,107,113);


(lib.Символ3 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.head();
	this.instance.setTransform(-60,-57);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-60,-57,120,114);


(lib.Символ1 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.body();
	this.instance.setTransform(-40,-49);

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-40,-49,80,98);


(lib.shape26 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFBAA").s().p("AhgA2IgHABQAHgTASgVIAognQAZgXANgEIAzgFIAVACIAdABIABABIACACQg8ATgYAUQgdAXgFAtg");
	this.shape.setTransform(-47.7,85.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFDF18").s().p("AjXDvQAEgsAggaQAXgTA8gUIgCgBIAAgCIgdgBIgWgBIg1AEQgMAEgaAXIgoAqQgRAVgIASIghADIAEgJQARguARgOQAngjAygWQAWgLAigBIA1gBQA3gEAAhAQAAgHgOgfQgPggAAgPIADADIAnAlQARAOAHAQIAKAfQAHAMATAAQAUAAAPgHQATgLALgcIAAAYQABARgQARQgKALgaASQgVAPgagDQgLgCgDAMQgEARgFAEIhCA2IgzAugAAWC8QANgTAUgVQAYgXAMAAIAZAAIAEgBIAPgCQAJAggrAPQg5AMgZAKgAAphnQgPgWAAghQgBgYAUgNQAMgJApgOIANAAQgfAsAABDIAAAmQgcgUgLgOgAEdjTQgRgMghAAIghABQgXACgSAIIgHAAQAXgRAlgIIA/gHQAjAAAMAJQAPAKAAAaIAAATQgDAKgJAEQggglgKgIg");
	this.shape_1.setTransform(-27.5,67.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#E78A0E").s().p("AhfErIgtgEIAzguIBCg2QAFgEAEgRQADgMALABQAaADAVgOQAagSAKgLQAQgRgBgRIAAgYQgLAcgTAKQgPAIgUAAQgTAAgHgMIgKgfQgHgQgRgQIgngkIgDgCQAAANAPAgQAOAhAAAGQAABBg3AEIg1ABQgiABgWAKQgyAXgnAiQgRAOgRAvIgEAJIhtAIQAKgJA5gnQAigXAJggQAIgcAtgfQAsgfAiABIAyAFQARAAARgWQARgYAAgZQAAgRgOgeQgSglgTAAQgaAAgXAOQgaARAAAaQABAIAFARQAGARgBANIgDAAQgHgNgUgSQgHgIAAgdQAAguAdgeQAcgcAogBQAWABApAQQArATABAQQALhXAegqIASgYQAIgKAAgLQAAgsg5AAQgUAAgoAMQg1APgFAVIAAgCQAAgsAYgUQAXgUAtAAQAwAAAmAnIAZAbQAMAMAGgBQAJABAvgUQAwgUA9AAQBMAABAAwQBEA1AABJQABBLgsAvQgtAzhIAAQgkAAgWgNQgcgSAAgmIABgZQADgNANgUIAAADQgDAZARAOQAQALAcAAQAeAAAAgiQAAgfgWgQQgUgPgiAAQgYAAgRAPQgSAQAAAeQAAASAXBjQAAAkgIAOQgMASglgEIAAAEQAXAAAKAFQAKAHAQgBIAcgBQAGgDAKgQIAAAfQgcAxhHAaQh6AsgbAQgAA+DGQgUAVgNASIgDAEQAZgLA5gMQArgOgJggIgPACIgEAAIgZAAQgMABgYAXgAA0iRQgUANABAYQAAAhAPAWQALAOAcAUIAAgnQAAhCAfgsIgNAAQgpAOgMAJgAEkihQAKAHAgAmQAJgFADgJIAAgUQAAgagPgJQgMgJgjAAIg/AHQglAHgXASIAHAAQASgJAXgBIAhgCQAhAAARANg");
	this.shape_2.setTransform(-28.2,62.5);

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-72.3,31.5,88.2,62);


(lib.shape25 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFBAA").s().p("AgMASQgMgDAAgNQAAgHAHgGQAKgIASACQAWAKgNARQgKAIgKAAg");
	this.shape.setTransform(-50,87.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFDF18").s().p("AmbDhIAAgSQAqhDAYgdQAogvBBgBQA7AAAigQQgKAVgiAZIgzAiIgDAAQBRAEBBg1QA+hBAcgTIAAASQgHAVgfAxQgbAtgHAgQAbgHAqgcQAigYAIgKQgIAQgSAVIghAkQgYAdgHAbIgSgDIg8gGIiJAJIhyAJgAjOCoQgGAGAAAJQAAANALACIANAAQAMABAKgJQAMgSgVgKIgIAAQgPAAgIAGgABMBRQAAgRAYgKIAMgFIAAAEIAJgIIALgIIAHgGQAQgNABgQIgFgMIgEgTQAKAIAVAJQASAKAAAOQAAAbgjAXQghAWglAAgACThcIgEgiIgEgcQAAgjAwgVQApgRA0AAQA8AAAeAfQAPAQAbA7IAAACQAAgFgDADQgNgNg/geQg7gdgGAAQgcAAgvApQguAoADAUgAhEiFQghgXgcgDIAAgCIASgGIAUgFQASAAAVAOQAYAPgBARQAAALAHAUg");
	this.shape_1.setTransform(-31.1,69.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#E18403").s().p("AkBECQAHgbAYgdIAjgkQATgVAHgQQgIAKgjAYQgqAcgbAHQAGggAcgtQAegxAHgVIAAgUQgcAVg+BBQhBA1hQgEIADAAIAygiQAigZAKgVIABgBQAxgXAAg9QAAgfgOgXQgTgdgmAAIgeAGQgXAIAAAKQAAATAHAVIABACQgQgZAAgZQAAglAighQAkgjArAAQA2AAAiAgQAqAnAABRQAAAWgEAVQgEARgDAFIADAAIAfgnQAWgbAEgcQAUhpAAgLQAAgPgWgMQgXgLggAAIgjAGIgcAFQgBgqA3gBQAoAAAZANQAWALAaAeQAdgYArgSQArgRAlAAQApAAAoARQAnARAVAZQANAQATANIAeASQAeAVAAAtQAABAgsAlQgsAnhSAMIgrAAIAAgCQAUgLArgOQAjgPAAgfQAAgggUgQQgTgPgoABIgvAFQguAKAAAQIAPAXQAOAXAAAZQAAA6hYA4Ii9BfgAgrAbIAEAOQAAAQgRANIgHAGIgLAIIgIAEIgNAFQgXAKgBARIAPADQAlAAAigWQAhgXAAgbQAAgQgQgKQgWgJgKgIgAgtg1QgCgUAtgoQAtgpAcAAQAGAAA7AdQA/AeANANQADgDAAAFIAAgCQgbg7gPgQQgegfg8AAQgzAAgnARQgxAVAAAjIAEAcIAEAiIADAAIAAAAgAk0iAIgSAGIAAACQAcADAhAXIAuAmQgGgUAAgLQAAgRgYgPQgVgOgRAAgAGci4IgLgXQgWgghFAAIAAgEQAlgRAdAAQAlAAARAUQAOARgDAfQgFAGgCAGQgBAHgMgBQgFAAgEgKg");
	this.shape_2.setTransform(-11.4,65.3);

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-72.3,39.2,105.2,52.9);


(lib.shape24 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E18403").s().p("AjkCrQgDgoAaghQAKgNAvgrQAIgGBmgjQBtgjAeAAQASAAAYAIQAhAJAQARIgDgwIgEgWIAEABQAKAFAGALIANAWIAaApQAUAlAAANQAAAqgJASQgMAagkARQgNhSgOgTQgIgNgxgOQgsgOgPAAQgdAAgbAQIguAiQgMAGgWAjQgZAogNANIguAsQgWAUgTAFIg0AOIgOADQAlgjgCgtgADVi7Qg+gbgOgSQAFgNAPgDIAZgCIAgACIAbAZQAJAJAFAWQAGAbADAFQgOgLglgQg");
	this.shape.setTransform(-13.2,67.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FBFD9B").s().p("AiuBtIgVhCQAAgNAXgIQASgGASAAQATAAACAdQABAQAAAeIADABIAHABQAIAAAJgRQAIgRAJAAQAFAAAFAIIgIAHIgJALIAGAWQAFAOAAAKQAAATgRANQgQALgYAAQgaAAgZhBgAimhGQAAgMAIgJQAJgJALAAQAJAAAMAGIAAAaIgJAPQgEAFgNAAQgXAAAAgWgABBhYQgJgEAAgJQAAgIADgEIAUgSIAUAMQgEAIgDATQgBAHgOAAgACOh8IgUgEQAAgcAMgLQAGgFALgBQAJABARAIQATAKAAAKQAAAIgIAIQgJAJgMAAg");
	this.shape_1.setTransform(-32.6,74);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFDF18").s().p("AkpDgIgwgMIgrgMQgJgHAAgiQAAg1A8gjQBBgbAKgHQAagQAfhJQAehIAAgjQAAgPgIgXQgGgUgGgLIACAAQAtAKAiAbIAwApQAMgOAGgYQADgMAWAAQALAAAiAWIAjAWIAlgWQAlgWAwAAQBHAAAtAVQAtAVARAnQAFAMAOAFIAOAFIAEAVIAEAxQgRgSghgJQgXgIgSAAQgfAAhvAmQhmAggHAGQgwAsgIAMQgZAhACAoQADAtgmAjIhBADQgrAAghACIg7ABgAihA8QgXAIAAANIAVBCQAaBBAZAAQAYAAAQgLQASgNgBgTQABgKgGgOIgGgWIAJgLIAIgHQgFgIgEAAQgKAAgIARQgJARgIAAIgHgBIgDgBQAAgeAAgQQgDgdgSAAQgTAAgSAGgAiTg1QgIAJAAAMQAAAWAXAAQANAAAFgFIAIgPIAAgaQgMgGgJAAQgLAAgJAJgABGhLQgDAEAAAIQAAAJAJAEIAMADQAOAAABgHQADgTAEgIIgUgMgACRiBQgMALAAAcIAUAEIAZAFQAMAAAJgJQAJgIAAgIQgBgKgTgKQgQgIgKgBQgLABgGAFg");
	this.shape_2.setTransform(-33.7,70.2);

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-73.5,42.3,86.8,50.9);


(lib.shape23 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFDF18").s().p("AktCOQAAgTANgOQAMgOAAgNQAAgWgUgKQgUgLAAgKQAAgyB7gyIAAACIgcARQgRAKAAAPQAAAbARAkQATArAVAAQAmAAARgRQALgLAGgcQAGgfAFgLQAMgXAcgJIAsgOQAbgLAOgPIAZgjQARgUAYAAIAYABIAZAPQgUAHgQAPIgnAfIhPApQgQAIgTAdQgTAfACASQAEAoghAsIgDAFIgtgDIhVgDQgVAAg0AOgACqh6IAAgJQACgGAJAAQAPAAAjAWQAiAVAMAAIAngLQAEAKgSAMQgRAMgUAAQhfgeAAgVg");
	this.shape.setTransform(-30.2,79.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E18403").s().p("AmODsQgRgPAAgYQAAgoATg+QAZhTAngJQA/gMAfgoQAfgngHg6QAqAHAAA8QAAAdAEAKQAHARAYAAQAoAAA7g1QA5g2AuAAQAZAAAUAMIAkAaQAyAlBIAAQAnAAAugSQAsgSAQgYIADAxQAAA0gaAdQggAohGAAQgsAAgbgKQgbgKgiAAQhHAAgkAfQgZAVgPAvQgRA5gHALQgUAfgrAAIgfgDIADgFQAhgsgEgoQgCgSATgfQATgfAQgIIBPgpIAngdQAQgPAUgHIgZgPIgYgBQgYAAgRAUIgZAjQgOANgbALIgsAOQgcAJgMAXQgFALgGAhQgGAcgLALQgRARgmAAQgVAAgTgrQgRgmAAgbQAAgPARgKIAcgRIAAgCQh7AyAAA0QAAAKAUALQAUAKAAAWQAAANgMAOQgNAOAAATIACAFIgBAAIgxANQgUAAgQgPgACdgoIAAAJQAAAVBfAcQAUAAARgMQASgKgEgKIgnALQgMAAgigVQgjgWgPAAQgJAAgCAGgADji4QgXgMgkgIIgygPQgfgIgZAAQgsAAgXAaQgZAZgEAAQgHAAgBgIIAAgNQAAgaBRgPQA9gMAzAAQAzAAAXAJQAhAMAIAZQAPARAAAXQAAAPgDAFQgDAAgDADQgSgbgbgQg");
	this.shape_1.setTransform(-28.9,70.1);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-70.5,45,83.3,50.3);


(lib.shape22 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#E18403").s().p("AmdDrQhlgOAAgcQAAhRA/hGQBAhHBkgYIAAACQgUAXgEANIgCAkIADAhQAFAOAWAAQAVAAAWgVIAqgtQA9hABQAAQAiAAAuAXQAvAXAkAAQAWAAAZgPQAggSAAgaQAAgZgNgUIgRgbQAWAJAZAZQAjAmAAAkQAAAqg/AxQhAAwg3AAQgOAAgWgRQgUgRgcAAQgSAAgWALQgUALAAAJQAAAJAGALQAFAMAAAGQAABBhTAaIgnAKIADgDQAOgQAIgfQADgLgBghQAAgfAHgRQAHgPASgRQAQgPATgLQANgHAhACIArADIAAgRQgJgMgOgDQgyAEgpAPQg0ATgVAiQgKARg2A0Qg+A6gUAAQgIAAgDgGIgDgLIAIgZQAJgUAAgJQAAgIgJgFIgKgDQgNAAgJAMQgIALAAAQIAEAZIAEAVQAAAbgCAHIgDAEgAndC3IASAAQAIgLAAgKQAAgKgGgCIgUgCgAl7AfIAAAOIAGABIAKACQAKAAAIgGQAHgFgBgGQgEgFgIgEIgHgDIgMAAgAAJAFQgIAEAAAPQAAAVBVAAQAiAAAhgTQAdgRARgWIg9AUIgjABIhEgGgAjOiXQgPgIAAgWQAAgaArgPQAngPA2AAQBEAAA3AMQA0AKAaAQQgzAAhpAbQhrAbgWAAQgaAAgLgGgAHBi3QAAgLAIgIQAKgJAPAAQANAAgDgDQAKgCAGAEQAHAFAAALQAAAeglAAQgdABAAgSg");
	this.shape.setTransform(-17.6,68.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFDF18").s().p("Aj+B7IADgFQADgHAAgbIgFgVIgDgZQgBgQAJgLQAIgLANAAIAKACQAJAFAAAIQAAAJgJAUIgIAaIADAKQADAGAIAAQAVAAA9g6QA2gyAKgRQAVghAygUQApgPAygEQAOADAJAMIAAARIgrgDQghgBgNAHQgTAKgOAPQgSARgHAQQgHAQABAdQAAAhgDALQgIAfgOAQIgCADIhlAIgAlRBEIAAgiIATABQAHACAAAKQgBAKgHALgAjqhCIgGgCIAAgNIAJgMIAMAAIAIADQAHADAEAGQABAFgHAFQgIAGgKAAgACMhZQAAgOAIgFIAbgDIBDAGIAjgBIA9gWQgRAYgdARQghATgiAAQhUAAgBgVg");
	this.shape_1.setTransform(-31.5,80.2);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-69.1,45,103.1,48.2);


(lib.shape21 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFDF18").s().p("ABHBDQgMgEAAgIQAAgIAPgXQAOgYAAgJQAAgQgHgFIgZgNQABAAABAAQAAAAAAgBQABAAAAgBQAAAAAAgBIAVgDIAYgDIAhAEIAdALQABApgRAdQgWAlgrAAgAiUAsQgRgSAAgdIABgeQAEgSARgGIAHAiQAHARATAAQAZAAArgbQAwggAQgEIAdAAIgoAgQgeAYgCANQgEASgYAWQgaAYgYAAQgfAAgSgUg");
	this.shape.setTransform(-47.9,81);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E78A0E").s().p("AiFETQgmgNggAAIhfAIIhLAHQhNAAAAhJQAAg0BDhtQAwhLAdgiIADAAIgSA7QgIAaAAATQAAAfAJATQALAXAXAAQAbAAAvgjQA1goAUgGQAEAiAXAMQARAIAoAAIAWAAIAfgLIANAAIAAAxQgKAOgDAeIgDATIgDARIgCAJQgKAigNASQgUAZgjAAgAhxB0IgVADQAAABAAAAQAAABgBAAQAAAAAAABQgBAAgBAAIAZAMQAHAGAAAQQAAALgOAYQgPAXAAAIQAAAIAMAEIAOADQArAAAWglQARgdgBgrIgdgLIghgEgAlnCEIgBAeQAAAeARATQASAUAfAAQAYAAAagYQAYgWAEgUQACgNAggYIAoggIgdAAQgQAEgyAgQgrAbgZAAQgTAAgHgSIgHghQgRAGgEASgABbh6QAAhlhuAAQgzAAgrATQgyAWgZApQAphVAkgbQAsgiBcAAQA7AAAZArQATAjAABEQAAArgIANIg5A/QAcgqAAg6gAE2hNIAAgaIAIgIIALgBIgBAJIABAKIgCAQgAFyhxQAAgKAJgLQAJgMAJAAIAbADQgEAKASACQANACAAAOQAAAQgJAIQgKAIgWAAQgoAAAAgeg");
	this.shape_1.setTransform(-28.4,64.3);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-73.5,35.4,90.3,57.8);


(lib.shape20 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFDF18").s().p("AitDUIAAgmQADgsAwAAIABAEIABAIIgFAgIAoAlIAAAAQgjAAgoAbIgQAKQAEgMgBgYgAANBzQgIgSAAgUIAIgZIgCAAQgGANgXAMQgYANgVAAQgiAAABgRQAAgYAoghQAXgQAUgKQAJAUAPABQAQABAcgdQAcgfALggQALggAGgnQAGgnAAgRQAAgWgEgSQAeAUAPAcQATAjAAAyIgCAXIgkBPQgdARgKAMQgGAFgRAnIgPAzQgJAYgUAAQgKAAgKgVg");
	this.shape.setTransform(-43.6,66.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E78A0E").s().p("AhgEVQgNgXgnACQgSABgcgIQgdgJgRAAIgogmIAFgfIgBgIIgBgEQgwAAgDArIAAAnQABAYgEAMQgaARgKAAQgTAAgagRQgdgTAAgTQAAgIAMgdIABgDQgGg1AvhBQAdgqBchgQgGAPg/BfIAAARQARABAzgwIBMhIIAEADIAOAzIAFAMQgUALgXARQgoAgAAAZQgBARAiAAQAVAAAYgNQAZgMAGgNIACAAIgIAZQAAATAIATQAKAVAKAAQAUAAAJgZIAPgyQARgnAGgFQAKgMAdgUQgZA+AAAvQAAARAPBoQAAARgLASQgNAVgPAAQgUAAgNgXgAB7C8QgGgEAAgIQAAgIADgDIALgDQAKAAADADQACADAAAKIAAAKQgCADgNAAgAGVB1QgMgFAAgNQAAgMAFgIQAHgJALAAQAIAAAGAGQAAAJAGAGQAGAFAAAGQAAAHgGAFQgFAFgIAAgAE2BJIgMgFQgFgGgBgFIABgIIAIgKIAZAUIAAAOgAAWhWQAAgxgTgjQgNgcgegVIgDgOQgHgWghgNQgggNg+A+Qg9A+gBBEQgXgvAmhJQAlhKA+gNQA8gOA3A3QA1A4AAAyQAAAggXA3gABZhbIAAgSIALgIQAKgGADAAQADAAAEAJQADAGAAADIAAALQgCAGgLAAgADliPQAAgIAOgHIAGgDIAmAEQAlAAAcgdQAbgbAAgfIAAgLIgGgJIAAgOQANASADAJIABAaQAAA2gmAhQggAdgqAAQgxAAAAgig");
	this.shape_1.setTransform(-28.1,63.7);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-72.3,33.6,88.5,60.1);


(lib.sprite27копия = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#78460E").s().p("AvOKFIgDgTIAEgNQACgLAHgIIAFgDIAIgCIAAgBQAUgCAPANIAFAGQAEAQgIAQQgGAKgLAGQgJAEgIAAQgOAAgLgMgAjwJaIgGgGIgggIIgKgXIh/gNQBmgbBpAPIAbgaIACgGIACgNQAXgZAggKIATgFIACgyQgagUgIgeQgHgbAOgYIgCgBIgBABIgHAJIgFAEIhGgJIimgIIgGgHQgRAEgRAHIgEACIgNgLQA3gJAfgkIgJgFQgWgNgOgPQgogrAdg9QAOgdAfgOIASgKQAMgYAVgPIAHgEIgNgDQgOgOADgXIABgGQgegWgXgiIhOgDQgLgNgIgQQg9BmhogWIgBACQgRgFgOgHIgBAAIgIgFQg1giAIhRQAGg7AvgpQBVhLBxAGQCUANgCCNIgDAGQAJARASAPQAXAVgFAdQBtgNAmBZIAGgPQANgZAVgTQgGgQgQgRQgUgTAAgcQhrANgNhcQgHg4A0gbQAbgPAbgGQAxAEApAeIAHAGQBcAzgUBkIgDAHIAFAFQADACAFABQAshuByAiQASAFAPAKQgCgcALgbQAEgKAGgJQgQgXgngYIgygjQgTAIgTADQhhArhUhaIgEgGQgTh3Bng5QAygeA6ATIAIgCQAWgjAogUQAagNAagGQCtgGA2CoQAIAZADAbIABABIABABIAHgGIADgCIAAgCIADACIAHAkIgRgQIABASIgBAHIgBACIABAAQBTAWA1BQIAFAFQCSgpBJB1QASAeADAlIgBAZQgQBDgwASIAGAGIACAGIgGATIADgBQCJghAiB/QAJAigOAhIgFALIgBABIABAAIAAgBQBFAugBBbQgBAKAIAJQAYAbgOAdIgtAVQhAAOhCgLIAJAeQACAOgMAIQhDAphNgUIgHgGQhAAbgzgXQgeAngyANQgaAHgXANIgMAAQg0AghCgtQgPgKgIgPIAAgNIgJgNIgCgGIADgHIgHgGQgQASgagSIgPADIgGAGIgCAZIhDAzIgLAEIgNgEIAAgNIgCABQhKAkhDAwIgOADIh6gIQgPAQgUAAQgXAAgdgXgAkPIwIABADIAJgFIgKgCgAA1IXIACgBIgCAAgAIgHBIAMAFIgKgHgADCHFIABAAIgBgCgAlHEZIA2gFIAAgGIgUgBgAi5DwIACAAIAAgBgAI6C4IABgCIgLgEgALvghIACgDIgCAAgAp3IoIgHgGIgOgLQguATgpgOQgBAAAAAAQgBAAgBAAQAAAAgBABQAAAAAAAAIgIALIgIgCIgFgEQAcg2BLgBQAQgUAHgYIAHgZIATgTIAKgDIAAgBIAgACQALAKACAPIABAZQgHAPgOAKIgSANQADAPAJASQAGALgCANIgFAGIgJAGgAsLG3QgJgdAcgLIALgJIAQAEIAJAFIAFATIABASIgDAGIgHAHIgkACgAsAEyQAzgPA8AAIARgRIANgDIAAgBQA0gHASArIABAGIgEAGIgEAEIgGADQgZACgYAAQhOAAhHgVgAv/EsIgBgHIgBgTIAEgGQAEgJAFgIIACgBIARgDIAYAOIAFAFIAAATIgZAXg");
	this.shape.setTransform(417.4,95.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#78460E").s().p("AigKgIgNgCIiagFQgqAGgNghQA0ggBAgGQANgPATgJQASgIATgBIARgWQAOgWAagHIgCgGIgHgLQgMgSgRgPIgEgZQgCgfAMgaIgDgFQgUAQgmgLIgIgJIgTAAIgRAEQgVAAgQgMIgDgCIh4gRQBFgNBKgCIAFgGIAEgEIACgCIACgBIAAgCQAsAUArAZIALAGIg0gqIACgEQAFgEAGgBQAmAMAkARIADgGQACgfAMgeIgGgXIAAgCQgTg3g1gqQgLgJgCgQQgKhFBLgEQgBgOAHgMIAHgMIgegqIgCgNQgCgJAJABQAVATASAWQgKgZgRgQIgPgJIgGAAIACgEIgEgGIADgFIAQgGIAHACIABAAIACACQAXAJAOASIADADIAaAuIAEgBIANgFQgjg7Alg7IARgYIAbgbIAfgHIABgBQBCAIAhAkQAagoAkgeIAUgOQgigggJgtQgFgWADgVQgOgMgpgMQgPgFgOgJQgKgHgJAPIgEAFQggAHgZgSIgFAAIgKAHIgHAKIgBACIgBAAQgQAQgeAGIgUACQg2AEg0gNQgTgPgNgRIgLgRQgeg4AmhJQASgiAigUIAZgCIgCAGIgIAHIAJgFQAsgYAxAOIAQACIgCgTIADgGIAFgTQAYgqAugMIAdgHQBJAHA0AnQAkAcAbArQAOAYAHAdIgDAHIgEAGIACAGIAAABQAUAxArAcIAXgDIAAgBQBcAaAQBNQAOgNAcgBIAAgBQCpApgbCpQgMBJhEAiQgdANgfABIgNATIA1AyQBdhQBVBTQAIAHgBALQAgAegKAoQgHAXgNAVQBHAKAyA9QANARgBAVQAFALAJAJIAFAGIAAAZIAmAmQg3Beh6gfIg1gPQg/gTgygbIgIAEIAHAMIADALQAUAJAPARIALAMIACANIgBAMIgBAHQhRAshfgMIgOAaQgNAWgaAJQhLAZhKghQg2gZg7gLIgFAHIiYAHIgCA4IgCANQgiAogwAAQgPAAgQgEgABVIKIAGABIgCgDgAKyD5IABADIAAgDgAB7AGIACgBIgGgFgACKgGIAEgCIgCgEgAlAEKIgFgEIAAgHIACgMIAJgOQAFgLAJgFQAZgCARARIAEAGQgBAtgbAAQgPAAgXgNgAoNEDIgIADQhjhBBPhWQAXgaAngCQAOgkAngRQAUgJARgDQB3AQgEBrIgDAaIg5AkQACBJhYgCIgeABIgIAAQgcAAgbgQgAtlgYQghgTADgmQAOi3CtgxQCBgEAxBXQARAgAHAsQADATgMASQgeArgfgwQgTAKgUgEIgPgEQgagLgXgOQAIAYgFAaIgEATQgLAigcAYQgkAOgiAAQgoAAgkgUgAtTgnIAGAAIAAgFgAndguQgEgJAAgKIAAgMQAKgOALgMIAEgGIALgDIAAgBQAjAJgCAlIgBAHQgPAWgVAAQgNAAgPgIgAjphWQgNgEgGgLIgBgDIgFgHIgCgeIgigKQgvAggrgkIgRAAIgKgHQgUhGAygwQAPgOAWgHIAVgIQAuARAeAmIACAEQA5gBAYAgQAOAUADAfQABAQgHAQIgIAGIgGAZIgcATg");
	this.shape_1.setTransform(432.6,88);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#78460E").s().p("AiGK0IhegRIB6gTIAGgGIABgGQAAgEACgDIAKgNIACgEIA3gGIgDgNIgBgZQALgMAOgHIAJgEQgugHgNgqIgBgGQAGgPAWAAIANgBIAQADIANAFQAJAPAEARIACAZIADAFIASAOQAKAUgOASIgPASQgEAKAFAKQAGAMgBANQgwAfg+AAQgcAAgdgGgAEyJNQhygehxAOIgZADIABgGIgBgZQgBgKADgJIAEgFIABgBQAOgPAVAAIAWgKQARgGAMgQIgGgWQgRgDgNgNIgKgKQhCAGg6gOIABABQh7Aph7hAIAFgMIAGgHQBNgYBQADQAKgLADgOIACgGQAvgTAsAuIBQgdQgPgWgSgiIgBgFQg+gEg0grIgGgkQhFAagXhNQgLglARgfIAAgNQBLhVBEBbIALACIAlgIIgCgHIgCgMIAAgGIAEgHQAGgKAJgGQhKgegDhKQgCg/A4gfIAEgNIAJgGIAfgPQBGgIAjA9IADAGQAcgVAiAFIAAAAIAFgHIAQgDIABgCIAOADIgRgHIAJgMQATAIAVACQAShFBEgLQBiAxgdBqQgFASgNAPQAeBThIA2IgHAGIADBFQAAAOgHALQBLAjASBFIAEgDQAfgGAeANQAQhQBOgMIAAgBQBfAUgjBbQgKAZgUASQBKgHAZBCQA4ALAdAtQAHAJgEANQhMBIhxgjQgXgIgYgCQARASgFAgIgBAHQhWAShYgHIgGgCQgeA9hGAAQgYAAgdgHgAHQILIAFgDIgCgEgAGvFuIAEgCIgCgFgAnFEiIhFAGQgrglgDg5QgCgtAfgfIAKgDIAAgBQBlgQAPBZIAAAHIAEABIAqAJQAdA5g9AZQgMAFgLAAQgQAAgPgJgAmTBcIABgGIAGgTIAVgJQAOgEAJgGIAgACIAOANIAPATIABAGIAAAMIgBAHQgeAXgZAAQggAAgZgmgAJKgDQgWgMgLgXIAAggQhehbBZhhQAUgXAZgKQB1AwgDCFQgCBJg9AiQgPAFgOAAQgPAAgOgFgAtgiNQADg9A+gKQAUgDAOgOQACgCADgBIATAIIAEAAIANAAQAVAUgIAfIgFATQAAAKAJAJIAIAGQAEASAAAUIAAATQgaAjgrALQhpgQAFhjgAi6h7IgMgNIgDgGIgCgGIgOgMIgEgHIgBgGQhAAghEgTIgLgbQgHgRABgUIADgFIAFgHQAFgeARgZQAQgXAXgCQA+AEAoAuIAEAFQBsAgg4BcQgKARgRAAQgHAAgIgDgAowiZQgMgFgFgLQhpAPgDhdIABgMIAQgaIAFgMIAdgMIAAgBQCCASgFB7IgBAGQgNAPgRAAQgJAAgLgFgAjIlpQgngRgFgpQgPhzB1gpQAfgLAggGQAxhtB6AEQBHAIAQA/IACAFQCCA7ghCJQgMA1g5gQQgZgIgOgVQhEAAgng1IgHgCIgEACIgCACIgKgCQgfAkgtAGQgaBThFAAQgeAAgngQg");
	this.shape_2.setTransform(428.4,84.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#78460E").s().p("AATK/IgIgEIgLgKQAZg0BEAFQAHgIgBgLQgBgKAHgGIARACQAfAbACAqIABANQg7ANhEAAIgKgBgADEJBQgCgNAHgMIAHgNQA4ghAjgxIgLgSIlfAEIgEgHIgBgEIgmgBIgEgDQBMgeBVARIALgMIAIgHQAEgNAIgMIAJgNIAMgEIAAgCQAWAIASATIAEAFIBAgJIAEACIBtgGIAGgGIANAAIgEgJIAFgFIAHgGIAAgBQAbAKAQAdIAEAHQAcBYglBSIgIANQhagFhZAQgAgJIXQAAgNAKgIIAHgGQAWAAARAOIAEAFQgOAfgRAAQgOAAgPgXgAK6HxQhigEhjgBQgPAAgLgMQgDgXAPgSQAPgRAWgJQgfgSgXghQgFgJAAgJQhUgIgbhNIgDgMIAFgFQAGgDAGgBIACgCIAEgMIAFgEIAMgFIAEgCQCBAPAOB+IAAAEQA6AaA6gLQgFg6AMg2QACgIAHgCIArgKIAIAGIALANIgBAZIgBAGIgWAYQgMAMgIAPQgDAOAIAMIASAeQA5gOAiAyIASAiQgtAehCAAIgLgBgAoGDTQgBgNADgMQASgZAdgKIAKgFQAugBAIAvIADAEIBBADQAGAIABAKIACAgQgxAmg5AbQhMgUgIhTgAC+D+IgNgHIgDgNIgGgMQgGgEgHAAIgIACIgCgBQgxAlg4g6QgQgQgJgVQhWAkgzhHQgIgLADgQQAIgtAjggIAGgXQAVgXAhASIARAGQgRg5AZg4QAcg4A7gOQA1AGAsAgIAHAEQAvgcAjAZIAEgBQCNCAhKCzQgnBehaAAQgMAAgOgCgAk+CDIgPgMIAAgTQAJgUATgJIAIgFIAXAJIAJAGIAGAZQgNAcgcAAQgIAAgKgDgAKEgOIgCgHIAAglIAFgGIAagUQghAGgngVQgegQgIgiQgIggATgZIgBgGIAAgGIABgNIAMgNQAPgSAUgFQB5AHgKB6IgEAZQAEANAJANQAQAXgIAbIgFAGIgWAXIggAHIgJABQgVAAgQgOgAsLgqQgVgWgPgcIgEgGQgGg6AzgYIAKgFIAUAGIAKAFQAHAPgGARIgEAMQAaAQAVAWQgBA8gtAAQgSAAgZgKgAGRiNQgEgZATgTIAJgBIAAgBQA8APgGBBIgCAGQgVAPgQAAQgeAAgJg3gAkaiRQg3g7AShIQADgMALgIQAWgQAUgJQB7gPAmBsQAYBAhDgKQgZgDgIgXIgJgOQgJAdgUAWQgUAVgaAAQgKAAgKgDgApmjeQgHgMAAgQIADgGIAFgHIADgGIgBgCQgHgBgHABIgCgKQAAgEABgCIAFgLIAEgCIAGgBIABgCQBlAJAUBVQAEANgKAJQgbAMgWAAQguAAgYgvgAh4ljQgUgBgRgMIgUgOQgIgZgGgZQgEgWAFgXIAvgzIABgGIABgNQA6hEBigBQAShLBOgIIAHgBQBmgQAkBZQAFAOAMAKQApAlAGA3IgEAGIgFAGIgIAFQAEBchWgYQgagHgYgOIgkgWQgIgVgTgMIgWgRIAAgeIgugOIgLgFIgHAIIgDAFQAIAcgLAcQgKAYgVAPQAHBphoAAIgIAAg");
	this.shape_3.setTransform(422.2,80);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#78460E").s().p("ALXJ6IgXgLQhDAJg8gRQABgUAJgUQAIgUASgOIAHgCIAGAAIAAgCQAvAIAiAlIAJAIIAEAGIAAAGIAXAFIAFADIgBAHIgLAMIgHAFgABmJGIgEgHIgEgMQAngYBAAFIALgJQALgIAFgJQAxAaA1AWIADAFIgCAFIgEAFIgGADgAGwGbIgFgHIgBgGQAAgOARgFIARgGQA3AFAAA2IgBAGQgXASgSAAQgcAAgNgtgAm4GgQgMgCgKgKIgLgMQgHgfAEggQACgQAGgQIAOgLIACgBIARgCQAPgBAMAHIAJAGIAFAMIADAHQAtgJAZAjIgBALIgBAIQgkA8g4AAQgMAAgNgDgADgEhQhCAdgyg0QhLAThHgWIgGgDIgCAAQgOgGgLgMQgPhDA9gvQATgPAWgHQgMiBCIgTQANgCAEgEQBHANAdA/IADAGIgCAHIAAAFQATAJARAVIAEAEIAIgDIAEgBQBPBOg1BoQgXAugnAAQgWAAgcgPgALoBPIAOgLIAdAKIAJAEQAGAdgYAUIgUAMQg/gWAxgqgAsdAiIADgMIAEgYIACgGIAEgDIAGgEIAAgCQBCAOgMBEIgBAHIgFAGIgIAEQgrgFgQgrgAJhgGIACg/QABgVAUgJIAIAAIABgBQBiAQAFBhIAAAGQgfASgbAAQgrAAgigrgAk3hHQgCgxAUgsQAIgSAOgFIAaACQBDAygdBSQgEANgLAGIgMABQguAAgfgmgApAhrIAAgaQAKgUAYgFIAEgCQBDALgBBBIgBAGQgTAJgSAAQglAAgdgmgAjJiVQgCgKACgJIAAgTQAGgGAIgCIAJgGQA1ANAMA0IAAAGIgHAMIgFAEIgOABQgoAAgWgkgAiylbQghhEBVgSIAagIIADgIIABgFIAAgGQAfgxA8ATIALAMIAMAHIAGgGIARgTQgHhSBLgbIAZgLIACgGIAEgFIAXgGQBWAMgGBVIAAAGQBIArgIBZQgFAxgyAJQguAIgegmQgEgJABgKQACgOAHgLIgGgaQgzATg7gbQgUAMgYAHQgCAagGAYQgGASgQAIQAIA1gdAwQgJAOgQAJQh+AAACh2g");
	this.shape_4.setTransform(418.1,64);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#78460E").s().p("AHoJKIAAgTIATgfIANgFQAaAHASAVIAEAGIgDATIgBAGQgGAMgLAHIgZACQgTgKgPgPgApJF4IAAgTQANgWAfAAIAAgBQAZgBALAVIAEAHQgNAsgYAAQgUAAgbgdgAinDGQgHgQgBgTQgDhSBPgdQAAg4ApgqQAZgaAhABQCKgHABB/QAAANgEANQAmAlgEA6QgCAmggAXIgDABIgUABIAJgVIgBAAQg0Ahg+gTIgMgCIgIANIgDAGQglAUgeAAQg1AAgehBgAIogFQg2gDAKg4QACgNAHgKIADgCIAIgBIAAgCQBVANgoA/QgHALgNAAIgBAAgAmUhCQgKgPAAgRIgBgZIAKgNIADgGIAKgFIABgBQBUARg4A8QgKALgMAAQgJAAgKgGgAkpkfQgxhkBNhIQAKgJAPgEIAdgLQAqgLAUAiIADAGIABAHIgDAZIgEANIgTAMQgMAIgJALQAcAlgKAuQgFAYgXALQgQAFgOAAQglAAgYgggACBmiIgFgGQgHgbAOgYIAGgMQAHgOAQACIAAgBQA6AfggA3IgFAHIgmACgAgZnzQgSgDgIgPQgDgeAQgYQAMgTASgPIARgCIAIABQAIABAAgEQAkgFAbAWIAHAGQgHBZhWAAQgLAAgQgCg");
	this.shape_5.setTransform(429.4,62.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#78460E").s().p("AjsFtIgEgFQgegFgPgYQgIgOADgSIgJgMQgGguAeggQASgUAaAKIAOAEQAAgXAPgPQAYgaAhgGQBpgJAABbQAAAjgXAcIADAGIAUAUIAEAGIABAGIgBANIALATQgIAfgiAHQgYAFgUgQIgEgGIgDgHQgeAegfAAQgcAAgdgbgAGBC6IgDgHIgBgMIAAgHQAEgLALgGIAOgIIAbAKIAHAFQAFANgFAMQgDAKgKAHQgJAEgJAAQgPAAgNgKgAm+ibQAAgRAHgRQAIgVALgVQAMgWAVgHIATACQAiAZgNAmIgEAMIgIAHIgJAMQAdAfgSAmIgHAUQgMACgKAAQg+AAAChSgAiPlMQgEgMAEgNQAHgVAOgNIAdACIAZATQAJAIAEALIgDAMQgHAQgRAIIgPABQgbAAgTgSg");
	this.shape_6.setTransform(441.6,39.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#78460E").s().p("ABYEdIgPgNIgBgGIgBgTIgCABIgbgBQgSgMgEgUIgEgfQAPgbAegKIAVgFIAJgPQALgRAQgEQBdAGgpBPIgMAaIACAGIAIANIABAHIgBAMQgKAPgOAIQgMAHgPACgAizjYQgEgJACgKIACgNIARgTQgCgGADgFIADgIQArAKgMAzIgCAHIgEAFIgIAHIgaACg");
	this.shape_7.setTransform(414.5,44.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(314.8,29.8,205.3,131.5);


(lib.sprite27 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#78460E").s().p("AgdG1IgFgLQhMAXhWAHQhQAGhKgeIgBgBQgwAZhAgVQhfBZhtg8IgCgGIAAgGQgyAOgegmQh4Adhjg4IABgGIAEgGIADgDIAcAEQBUgHBSgQIANgyQACgNAGgNQAwgIAtAXQgEhZAqhPQAWgrAvgFQBYAYgZBfIgCAHQBEgQA2AnQABAPgKALIgOASIAuAeIAEAEQBXAAgXBIQgDAIgJAFIAAAAIAlAHQgFgHAAgKIgEgfIADgEQAJgFAJgCQAjg4BHAIQAxg7BNgTQgig7AYgnIgPgNQhLAYg2g+IgCgEQhUgRhhgIIibgRQgDgBgCgGQBggcBogBQgGgYAKgUQAOgdAegMQg8hMgQhfQgLg6A0gXQBjAKAjBdIACAGQAVAJAcAAIAPAEQARAdADAiQACAiAgARQA7gRAzAmIAEAGIABAGIABAFIAAgcIgCgUQgnhzBzgxQAQgGASgBQBUAFAwA9QAMgPASgNQAfgWAmgIIAAgZQAAgNACgMQAKgOAPgHQAggQAmAFQAEgnASgjQAZgzAygDQCSgLAQCDQADAagKAYIgKANIAKAMQAcAEAZANQATAKAIAUQAcAIAeANQAaAKALAZIgBAHIgEAMIgNAUIgDAGQBdBwhtBTIgUAQQAVBPgsBIIAEAMIALATIgBAHIgBAGQAUAkgYAgIgiAlQglAOgngIIgJgFIgMgFQhjAjhhgpIgMAAQg2Adg4gbIgOAfQgHAOgMAJIgFACIgVAFQh1BmiggpQgeAQgYAAQgqAAgYg4gAleGbIAAADIAjAIQASAHgMgPIADgEgAi3FUIgKAHIgDADQAPADAZgNQADgFgHAAQgHAAgQAFgABKBzIABgDIgFgBgANUBgIAEgBIgBgCg");
	this.shape.setTransform(353.6,118.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#78460E").s().p("AigIAQgdgSAHghIAEgTQg5ANgmgqQhcA8hvggQgzAhg/gRQhtBDh/gzIgSgNIgMgLQhWAFg+gwIgaABIASgGIgIgHIAOAFIBCgUIAJgEIAAgMIACgNQAkgwA9AXIABgDIABgGIAAgNIAGgGQAIgMAMgIIAHgFIAxgCQgjhOAphMQASgfAcgXIAPgBIAGgCQBdAIADBgIABAGQAxAJAPAwQAFAOgBAPIA0AbIAKARIADAAQAjAFAXAaQANgKAWgEIAygGQAYgtA0gLIAugDIAEgGIAXgYIAogEQgtgqAAgzQgWgBgRgNQg3APgzgdQgegQglABIgogBIgFgGIgBgGIABgBIgBAAQhZgXhggOQBfgeBtgOIAOgMQAVgRAcgFIgGgGIAAgHIAEgsIALgMIgCgBQhLgjgLhOQgNhhBngTQB7gEAWB0IAAAEQAOAFAPAJQAeASAAAjIARAFQAXAIAVAKIAogPQgCghAJgiQAShHBEgVQBpgNAzBWIAEAFQAmgMAfAFQAOgyAvgaQAVgMAZAAQgahZAphOQAUgnAtAAIAeAAQBigFAiBdIAAAEQBcALARBSQACANgDAMQBUAxAFBgIAAAQIADgDQBIA6g0BaIgDAGQAfAjATApQBtABACBuQAAAOgOAGIhDAVIgCAWIgfgBIABgBIAFgGIgBgHIgBAAQhKAShBADIgbgGIgLgEQASAHAQAMQAHAPAEARIABAMIARABIgCALQgEAPAFAQIgaABIgJALIgbAEIgEAGIgEAEIgDACQheAshXgfIhUgRIgGgGQgRADgZAKQgbBchmgBIhLADQg/BqhqhOQg4Ayg8AAQgtAAgugbgAnOGnIABAAIgBgCgApCGlIABAAIAAgEgAl2FcIAAgDIgCgBgAOqBuIADgIIgGgCg");
	this.shape_1.setTransform(371.8,117);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#78460E").s().p("AgsI7QgfgLhhAKIBBABQghAMgggNQgjgOgYgcQgDgQAAgQQAAgKADgJQgogYg9gIIgEgBQhYBCh0gpQhJAPg7AxQgQANgVAAQhkABhVgyQgPgJgSgBIhegNQgDgBgCgGIAHgFIAQgEIgxgCIgQgMIAEgDQAEgBAEAEQA8ACA6gPIAFgLIAGgSIAMgIIALgJQAOgqAxgEIAVgBQgBgeASgYQANgRAUgIQgyhAAbhJQAMggAhgLQBGgWAvAsQATARAPAbIAFAfIABAmQAVAQARAdQAGAKAAANQAjgEAaAXIANAMQAXgDAZAIQAQAFAOAHQAxgvA/AgQAvgeA4ABIACAAIgCgGIAAgHIAHgMIAFgHQhTg9APhOQjDA3jEhJIgFgHIgDgGQBChCBtAaQAugpA9AIIATABQgDgMAHgMQAPgaAdgLQgkgigXgrQgPgcAQgbQg+g+AzhCQAngxA+AGQCfABAICiQABAQgIAPIAEAMIgDAGQgHAJACALIA6AOQgchSA8hNQANgVAagIIAngJQA1ACAfAqIAEAGIADANIAyACIARAEQAZg2A3gDIAFgBIgFgFQAAgOAHgMQAIgPAOgJQhShrBkhWQAxgqBAgBQBfAKAdBdIACAGQBPAeARBPQACANgBANQBDAbAXBCIABAAIAEgDQA5AwgBBXIgDA6IAAgBIAagLQCHAggTCGIgCAHQBkAlgLBuIgFATQh3AciDgEQgRgBgPgGQABAXgJAZQgQAsgtgIQh9CFiihNIgIgFIgNALQgTAQgZgCQhKB8iZgmQgvAyg/AAQgeAAglgNgALjBFIAEgDIgEgDgANygfIAGAIIADAGIAFgIQgFgEgHgDgAFIknIgJADIALABIABAAIACgIg");
	this.shape_2.setTransform(382.2,113.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#78460E").s().p("AhYJRIgZgMQhYAyg4hFQgMgPAHgVQgYgMgygGQg5gHgmgdIAAgBQhbAzhtgIQhMAvhWAGQgfACgegCIh1gPQhMgPhLgUIgjgBIAAgKIgCgFIADAAIABgEQBTgYBYgDQA2hBBEAsIACAGIABAGIgBAEQAVgbAggKIAfgLQgEgYAPgUIAVggQhzhiBihiQAPgQASgEQAuADAdAUIALgJIgEgCIAIgBIAAgBQAegSAhAIIAJABICHgMQAzg3BOgEIASgTIAFgGIgRgTIgGgXQgEgTABgTQhegUgQhfQgMhDA/gdQAhgQAhAAQB2AGAKB0IAAAGIgCACQAJAPgCATIgBAGIgEAEQAXAOAHAYIAGgIQAOgYAcgIQgIhVAihMQATgrApgJQCPAEgECMIAAAGIAFAFIATAPIAEAFIAEAEIAZADQgrhsBZgxQAcgQAbANQhRiWCJh0QAoghAtgLQCBALALCAQADAhgRAeQAsAnAIA+QACAXgDAWQA0AAAkAmQArAQAeApIAJAIQApBKgIBEIAPgGQCYAYgOCOIgDARIANgCQB8AgA6BnQAEAIgDAJIgXAXQitAoingpQANAbADAiQABASgSAKQgtAYg0AAQg1AlhLgbQhqBRiEgpQhKBhhzgsIgVgJQg+BAhJAAQgkAAgmgOgAFPHdIAAAAIAAgBgAKDGrIAJgBIgJgHgAnMF1QAxAEAyAXIAGATIACADQAog7BPgJIAOgEIAogPQgCgTADgTIAJgsQgkgWgSgbIiGgDIg6ACQhkANhkgRQAIAYAAAgIAAAGIAUAVQAIAHACAKIACAAQBVAAAfBKgApyCxIAMgCIgQgEgAoYCoIAIAAIAAgDIgEgBgALRCDIABACIACgCg");
	this.shape_3.setTransform(393.3,107.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#78460E").s().p("AhIJlIgGgGIgBgHIgBgEIgogLQhKA0g/g6IAAgZQAEgNANgGQg5gRhagPIgFgHIgCgFQAsgVA5gJIAHACIAlgVQAYgQAfABIADgKIACgNQASgWAcgKIAGgDQgFgaATgSIAWgUIgRglQhaAQghgzIk7AaQhVgBhTgTQADAWgNAgQgFAPgRABQhUAEAIhRQADgcAXgQQA2ADASAZQBcg5ByALIBMgDQAJghAdgPQAngTAaAjIAIACQAOgHALgKIAJgyQACgRAMgOIANgUIgWgqQgGgNADgNIACgSQhKgHhCgvQgogHAIg8QAMhdBhgQQCqAIAlChQAHAhgQAeIAEADQAPAGAKAMQAHAKgDAJIgCAGIgEAEIgIAGIgBACIAFgBIAIAAQAUgYAhgIQg2iGBxhaQAHgFAKgBIAbgDQBiAaAOBTQALghAfgZQAqgjA5AWQADgKgBgKIAAgGQicg8AgieQAFgaANgWQARg0BNgVQAigKAggEQC+gJAWC3QADAUgCAUIACgBIAMgCIAAgBQB2A5gqBuIACADIACAAIAPgFIAAgBQByABBMBTIAIAHQA5BZgSBOQAKgGAMgDQB+AEATB9QAJA5gkAtQBOAOA7A5QAXAXgLAeQgeAYgpgDIgEAFIgDACQhGAUhEgVQglgMgnAEQgoAFgjgLIAEAmQABAPgNAJQhMA7hUgRQgcAZg4gQQhLgUhJAIIghAFQgrAKgcgUQgQAZgXAGQgyBUh1ggQg8A8hMAAQgRAAgSgDgAB8IKIADABIACgHgAMjFiIAAgBIAAAAgALaCHIAAAAIAAAAgAybI4QAFgGAGgCQAKgFANgBIAGgFIAFgGQBOgCBLANQAhgZApgNQAvgHAWAoQBAgGAwgsQAHgLgDgOQgEgQACgQIATgZIgbhSQAHgXAfABQAKAAAEgFQAogEAbAeIADAFQAKAJAMgLIASgNQBRALgTBIQgFATgPAMQBCAFAkA9IADAGQg/AxhMglQgRgCgLAMIgOAUQhJAihTgLIgFgHIgBgEIAAgBIgPgDIgKAHIgHAGIABAGIgBAGQhUAZhTAAQhsAAhqgqgAtTI+IAJgDIgEgEg");
	this.shape_4.setTransform(400.1,103.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#78460E").s().p("AyYJuIgGgLQgBgDgDgBQAGgXAsgDIAAgBIATACIAOgCQAYgBANATIACAEIARANIAEAFQggARgiAAQggAAgjgPgAyFJeIgGABIAEADIADgFgAucJ2IgCABIgRgBIgDgEIgJgCIgXACIgGgCIAugaQAHgJADgLIAcgGQAKgBACgGIAMAAIAOgGQAkANAEAmIAAAGQgnAQgmAAQgNAAgMgCgAteJZIASgEIgGgMgAkCI+QgGgIABgJQhGgXhPgDQBGgqBaAFQAdgcAogCQAMgxAxgQIADggIgBgMIADgEIgDgEQgUgYABgfIgIgNIgHgFIgIgFIgIAIIlzAPIgEADIgPgCIgOABIACgCIgwADIgJgIIgBgEIiIgMQAwgoBNACICPAMIAJgSQADgKAIgHIAFgBQAcgYApAfIAHAGIA9gRIANgQQgag9A3hIQARgWAVgOIgCgEIgPAIIgIgGIgNgNIgEgFIgCgFIgBgGIgDgEQgUgJgXAEIgIgGIgagbIgCgFIgKAAQgUAQgWAKIgqAQQiIgKAGiCQADhJA/gqQAvgeAygJQBogRA+BNIAHAHIAEAUQAEASgEATQgDAMABANQACAPASAHQAPAGAJAOQA4AIATA0QAKAfgRAZIgPAAIAAABQAjAFAbANIgBgEIAFgMQAFgKAIgIIALgMIgFggQgFgcAAgdIAAgGQiGgyBNh0QARgaAdgCQCbAJAZCUQAFAgALAeIACABQAFglApgiQArgmA9ADQgCgPAEgOIADgNIABgRQgkgGgegUIgKgGIgKAHQhKANg1gkIgCACQhag7A4hoQAohIBXgJQAjg9BGgPIAsgGQCwgHAvCgQASA6ANA6QACAIAHAJQAlAvAYA1QAUgQAYgOQAKgFALgCIAHAGIAggEIAfgNQCJAfAACQIgCAWQA4AaABBCIgBAGQBAAyAaBTQALAjgUAgQA3AoA+AgQBQAqgZBFQiEASiHAEIgEAAIAMAMIAGAZIAAATIgOATIgTAEQhcA2hGg8QhJALg7gjQhiBTh3hVQgpAlg2gBQhPCAiMgqQhHA8hZgkQgrAfglAAQgxAAgng0gAhHI1IABAAIAAgGgABbIiIADAAIAAgFgADoEqIAHAHIgBgNgAhfAZIABABIACgBgArpJIQgFgMgCgNIgBgNQAUgwAygPQgfgtgTgzQgCgFABgGQANgOASABQA6AIAFA5IADAHQARAQAXgXQAOhIBDAsQAGAEACAKQACAJgDAKIgmAyQALATAiATQAzABAWApQhNAdhagmQg/gag7AyQgIAIgKAAIgJgCgAt/EnIgBgBQgMgFgLgMIgCgNIAAgfIAEgGQAHgJAJgDIABgBIAZACQAMAHAHALIAPAUIgDAZIgkAVg");
	this.shape_5.setTransform(408.1,99.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#78460E").s().p("AvOKFIgDgTIAEgNQACgLAHgIIAFgDIAIgCIAAgBQAUgCAPANIAFAGQAEAQgIAQQgGAKgLAGQgJAEgIAAQgOAAgLgMgAjwJaIgGgGIgggIIgKgXIh/gNQBmgbBpAPIAbgaIACgGIACgNQAXgZAggKIATgFIACgyQgagUgIgeQgHgbAOgYIgCgBIgBABIgHAJIgFAEIhGgJIimgIIgGgHQgRAEgRAHIgEACIgNgLQA3gJAfgkIgJgFQgWgNgOgPQgogrAdg9QAOgdAfgOIASgKQAMgYAVgPIAHgEIgNgDQgOgOADgXIABgGQgegWgXgiIhOgDQgLgNgIgQQg9BmhogWIgBACQgRgFgOgHIgBAAIgIgFQg1giAIhRQAGg7AvgpQBVhLBxAGQCUANgCCNIgDAGQAJARASAPQAXAVgFAdQBtgNAmBZIAGgPQANgZAVgTQgGgQgQgRQgUgTAAgcQhrANgNhcQgHg4A0gbQAbgPAbgGQAxAEApAeIAHAGQBcAzgUBkIgDAHIAFAFQADACAFABQAshuByAiQASAFAPAKQgCgcALgbQAEgKAGgJQgQgXgngYIgygjQgTAIgTADQhhArhUhaIgEgGQgTh3Bng5QAygeA6ATIAIgCQAWgjAogUQAagNAagGQCtgGA2CoQAIAZADAbIABABIABABIAHgGIADgCIAAgCIADACIAHAkIgRgQIABASIgBAHIgBACIABAAQBTAWA1BQIAFAFQCSgpBJB1QASAeADAlIgBAZQgQBDgwASIAGAGIACAGIgGATIADgBQCJghAiB/QAJAigOAhIgFALIgBABIABAAIAAgBQBFAugBBbQgBAKAIAJQAYAbgOAdIgtAVQhAAOhCgLIAJAeQACAOgMAIQhDAphNgUIgHgGQhAAbgzgXQgeAngyANQgaAHgXANIgMAAQg0AghCgtQgPgKgIgPIAAgNIgJgNIgCgGIADgHIgHgGQgQASgagSIgPADIgGAGIgCAZIhDAzIgLAEIgNgEIAAgNIgCABQhKAkhDAwIgOADIh6gIQgPAQgUAAQgXAAgdgXgAkPIwIABADIAJgFIgKgCgAA1IXIACgBIgCAAgAIgHBIAMAFIgKgHgADCHFIABAAIgBgCgAlHEZIA2gFIAAgGIgUgBgAi5DwIACAAIAAgBgAI6C4IABgCIgLgEgALvghIACgDIgCAAgAp3IoIgHgGIgOgLQguATgpgOQgBAAAAAAQgBAAgBAAQAAAAgBABQAAAAAAAAIgIALIgIgCIgFgEQAcg2BLgBQAQgUAHgYIAHgZIATgTIAKgDIAAgBIAgACQALAKACAPIABAZQgHAPgOAKIgSANQADAPAJASQAGALgCANIgFAGIgJAGgAsLG3QgJgdAcgLIALgJIAQAEIAJAFIAFATIABASIgDAGIgHAHIgkACgAsAEyQAzgPA8AAIARgRIANgDIAAgBQA0gHASArIABAGIgEAGIgEAEIgGADQgZACgYAAQhOAAhHgVgAv/EsIgBgHIgBgTIAEgGQAEgJAFgIIACgBIARgDIAYAOIAFAFIAAATIgZAXg");
	this.shape_6.setTransform(417.4,95.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#78460E").s().p("AigKgIgNgCIiagFQgqAGgNghQA0ggBAgGQANgPATgJQASgIATgBIARgWQAOgWAagHIgCgGIgHgLQgMgSgRgPIgEgZQgCgfAMgaIgDgFQgUAQgmgLIgIgJIgTAAIgRAEQgVAAgQgMIgDgCIh4gRQBFgNBKgCIAFgGIAEgEIACgCIACgBIAAgCQAsAUArAZIALAGIg0gqIACgEQAFgEAGgBQAmAMAkARIADgGQACgfAMgeIgGgXIAAgCQgTg3g1gqQgLgJgCgQQgKhFBLgEQgBgOAHgMIAHgMIgegqIgCgNQgCgJAJABQAVATASAWQgKgZgRgQIgPgJIgGAAIACgEIgEgGIADgFIAQgGIAHACIABAAIACACQAXAJAOASIADADIAaAuIAEgBIANgFQgjg7Alg7IARgYIAbgbIAfgHIABgBQBCAIAhAkQAagoAkgeIAUgOQgigggJgtQgFgWADgVQgOgMgpgMQgPgFgOgJQgKgHgJAPIgEAFQggAHgZgSIgFAAIgKAHIgHAKIgBACIgBAAQgQAQgeAGIgUACQg2AEg0gNQgTgPgNgRIgLgRQgeg4AmhJQASgiAigUIAZgCIgCAGIgIAHIAJgFQAsgYAxAOIAQACIgCgTIADgGIAFgTQAYgqAugMIAdgHQBJAHA0AnQAkAcAbArQAOAYAHAdIgDAHIgEAGIACAGIAAABQAUAxArAcIAXgDIAAgBQBcAaAQBNQAOgNAcgBIAAgBQCpApgbCpQgMBJhEAiQgdANgfABIgNATIA1AyQBdhQBVBTQAIAHgBALQAgAegKAoQgHAXgNAVQBHAKAyA9QANARgBAVQAFALAJAJIAFAGIAAAZIAmAmQg3Beh6gfIg1gPQg/gTgygbIgIAEIAHAMIADALQAUAJAPARIALAMIACANIgBAMIgBAHQhRAshfgMIgOAaQgNAWgaAJQhLAZhKghQg2gZg7gLIgFAHIiYAHIgCA4IgCANQgiAogwAAQgPAAgQgEgABVIKIAGABIgCgDgAKyD5IABADIAAgDgAB7AGIACgBIgGgFgACKgGIAEgCIgCgEgAlAEKIgFgEIAAgHIACgMIAJgOQAFgLAJgFQAZgCARARIAEAGQgBAtgbAAQgPAAgXgNgAoNEDIgIADQhjhBBPhWQAXgaAngCQAOgkAngRQAUgJARgDQB3AQgEBrIgDAaIg5AkQACBJhYgCIgeABIgIAAQgcAAgbgQgAtlgYQghgTADgmQAOi3CtgxQCBgEAxBXQARAgAHAsQADATgMASQgeArgfgwQgTAKgUgEIgPgEQgagLgXgOQAIAYgFAaIgEATQgLAigcAYQgkAOgiAAQgoAAgkgUgAtTgnIAGAAIAAgFgAndguQgEgJAAgKIAAgMQAKgOALgMIAEgGIALgDIAAgBQAjAJgCAlIgBAHQgPAWgVAAQgNAAgPgIgAjphWQgNgEgGgLIgBgDIgFgHIgCgeIgigKQgvAggrgkIgRAAIgKgHQgUhGAygwQAPgOAWgHIAVgIQAuARAeAmIACAEQA5gBAYAgQAOAUADAfQABAQgHAQIgIAGIgGAZIgcATg");
	this.shape_7.setTransform(432.6,88);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#78460E").s().p("AiGK0IhegRIB6gTIAGgGIABgGQAAgEACgDIAKgNIACgEIA3gGIgDgNIgBgZQALgMAOgHIAJgEQgugHgNgqIgBgGQAGgPAWAAIANgBIAQADIANAFQAJAPAEARIACAZIADAFIASAOQAKAUgOASIgPASQgEAKAFAKQAGAMgBANQgwAfg+AAQgcAAgdgGgAEyJNQhygehxAOIgZADIABgGIgBgZQgBgKADgJIAEgFIABgBQAOgPAVAAIAWgKQARgGAMgQIgGgWQgRgDgNgNIgKgKQhCAGg6gOIABABQh7Aph7hAIAFgMIAGgHQBNgYBQADQAKgLADgOIACgGQAvgTAsAuIBQgdQgPgWgSgiIgBgFQg+gEg0grIgGgkQhFAagXhNQgLglARgfIAAgNQBLhVBEBbIALACIAlgIIgCgHIgCgMIAAgGIAEgHQAGgKAJgGQhKgegDhKQgCg/A4gfIAEgNIAJgGIAfgPQBGgIAjA9IADAGQAcgVAiAFIAAAAIAFgHIAQgDIABgCIAOADIgRgHIAJgMQATAIAVACQAShFBEgLQBiAxgdBqQgFASgNAPQAeBThIA2IgHAGIADBFQAAAOgHALQBLAjASBFIAEgDQAfgGAeANQAQhQBOgMIAAgBQBfAUgjBbQgKAZgUASQBKgHAZBCQA4ALAdAtQAHAJgEANQhMBIhxgjQgXgIgYgCQARASgFAgIgBAHQhWAShYgHIgGgCQgeA9hGAAQgYAAgdgHgAHQILIAFgDIgCgEgAGvFuIAEgCIgCgFgAnFEiIhFAGQgrglgDg5QgCgtAfgfIAKgDIAAgBQBlgQAPBZIAAAHIAEABIAqAJQAdA5g9AZQgMAFgLAAQgQAAgPgJgAmTBcIABgGIAGgTIAVgJQAOgEAJgGIAgACIAOANIAPATIABAGIAAAMIgBAHQgeAXgZAAQggAAgZgmgAJKgDQgWgMgLgXIAAggQhehbBZhhQAUgXAZgKQB1AwgDCFQgCBJg9AiQgPAFgOAAQgPAAgOgFgAtgiNQADg9A+gKQAUgDAOgOQACgCADgBIATAIIAEAAIANAAQAVAUgIAfIgFATQAAAKAJAJIAIAGQAEASAAAUIAAATQgaAjgrALQhpgQAFhjgAi6h7IgMgNIgDgGIgCgGIgOgMIgEgHIgBgGQhAAghEgTIgLgbQgHgRABgUIADgFIAFgHQAFgeARgZQAQgXAXgCQA+AEAoAuIAEAFQBsAgg4BcQgKARgRAAQgHAAgIgDgAowiZQgMgFgFgLQhpAPgDhdIABgMIAQgaIAFgMIAdgMIAAgBQCCASgFB7IgBAGQgNAPgRAAQgJAAgLgFgAjIlpQgngRgFgpQgPhzB1gpQAfgLAggGQAxhtB6AEQBHAIAQA/IACAFQCCA7ghCJQgMA1g5gQQgZgIgOgVQhEAAgng1IgHgCIgEACIgCACIgKgCQgfAkgtAGQgaBThFAAQgeAAgngQg");
	this.shape_8.setTransform(428.4,84.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#78460E").s().p("AATK/IgIgEIgLgKQAZg0BEAFQAHgIgBgLQgBgKAHgGIARACQAfAbACAqIABANQg7ANhEAAIgKgBgADEJBQgCgNAHgMIAHgNQA4ghAjgxIgLgSIlfAEIgEgHIgBgEIgmgBIgEgDQBMgeBVARIALgMIAIgHQAEgNAIgMIAJgNIAMgEIAAgCQAWAIASATIAEAFIBAgJIAEACIBtgGIAGgGIANAAIgEgJIAFgFIAHgGIAAgBQAbAKAQAdIAEAHQAcBYglBSIgIANQhagFhZAQgAgJIXQAAgNAKgIIAHgGQAWAAARAOIAEAFQgOAfgRAAQgOAAgPgXgAK6HxQhigEhjgBQgPAAgLgMQgDgXAPgSQAPgRAWgJQgfgSgXghQgFgJAAgJQhUgIgbhNIgDgMIAFgFQAGgDAGgBIACgCIAEgMIAFgEIAMgFIAEgCQCBAPAOB+IAAAEQA6AaA6gLQgFg6AMg2QACgIAHgCIArgKIAIAGIALANIgBAZIgBAGIgWAYQgMAMgIAPQgDAOAIAMIASAeQA5gOAiAyIASAiQgtAehCAAIgLgBgAoGDTQgBgNADgMQASgZAdgKIAKgFQAugBAIAvIADAEIBBADQAGAIABAKIACAgQgxAmg5AbQhMgUgIhTgAC+D+IgNgHIgDgNIgGgMQgGgEgHAAIgIACIgCgBQgxAlg4g6QgQgQgJgVQhWAkgzhHQgIgLADgQQAIgtAjggIAGgXQAVgXAhASIARAGQgRg5AZg4QAcg4A7gOQA1AGAsAgIAHAEQAvgcAjAZIAEgBQCNCAhKCzQgnBehaAAQgMAAgOgCgAk+CDIgPgMIAAgTQAJgUATgJIAIgFIAXAJIAJAGIAGAZQgNAcgcAAQgIAAgKgDgAKEgOIgCgHIAAglIAFgGIAagUQghAGgngVQgegQgIgiQgIggATgZIgBgGIAAgGIABgNIAMgNQAPgSAUgFQB5AHgKB6IgEAZQAEANAJANQAQAXgIAbIgFAGIgWAXIggAHIgJABQgVAAgQgOgAsLgqQgVgWgPgcIgEgGQgGg6AzgYIAKgFIAUAGIAKAFQAHAPgGARIgEAMQAaAQAVAWQgBA8gtAAQgSAAgZgKgAGRiNQgEgZATgTIAJgBIAAgBQA8APgGBBIgCAGQgVAPgQAAQgeAAgJg3gAkaiRQg3g7AShIQADgMALgIQAWgQAUgJQB7gPAmBsQAYBAhDgKQgZgDgIgXIgJgOQgJAdgUAWQgUAVgaAAQgKAAgKgDgApmjeQgHgMAAgQIADgGIAFgHIADgGIgBgCQgHgBgHABIgCgKQAAgEABgCIAFgLIAEgCIAGgBIABgCQBlAJAUBVQAEANgKAJQgbAMgWAAQguAAgYgvgAh4ljQgUgBgRgMIgUgOQgIgZgGgZQgEgWAFgXIAvgzIABgGIABgNQA6hEBigBQAShLBOgIIAHgBQBmgQAkBZQAFAOAMAKQApAlAGA3IgEAGIgFAGIgIAFQAEBchWgYQgagHgYgOIgkgWQgIgVgTgMIgWgRIAAgeIgugOIgLgFIgHAIIgDAFQAIAcgLAcQgKAYgVAPQAHBphoAAIgIAAg");
	this.shape_9.setTransform(422.2,80);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#78460E").s().p("ALXJ6IgXgLQhDAJg8gRQABgUAJgUQAIgUASgOIAHgCIAGAAIAAgCQAvAIAiAlIAJAIIAEAGIAAAGIAXAFIAFADIgBAHIgLAMIgHAFgABmJGIgEgHIgEgMQAngYBAAFIALgJQALgIAFgJQAxAaA1AWIADAFIgCAFIgEAFIgGADgAGwGbIgFgHIgBgGQAAgOARgFIARgGQA3AFAAA2IgBAGQgXASgSAAQgcAAgNgtgAm4GgQgMgCgKgKIgLgMQgHgfAEggQACgQAGgQIAOgLIACgBIARgCQAPgBAMAHIAJAGIAFAMIADAHQAtgJAZAjIgBALIgBAIQgkA8g4AAQgMAAgNgDgADgEhQhCAdgyg0QhLAThHgWIgGgDIgCAAQgOgGgLgMQgPhDA9gvQATgPAWgHQgMiBCIgTQANgCAEgEQBHANAdA/IADAGIgCAHIAAAFQATAJARAVIAEAEIAIgDIAEgBQBPBOg1BoQgXAugnAAQgWAAgcgPgALoBPIAOgLIAdAKIAJAEQAGAdgYAUIgUAMQg/gWAxgqgAsdAiIADgMIAEgYIACgGIAEgDIAGgEIAAgCQBCAOgMBEIgBAHIgFAGIgIAEQgrgFgQgrgAJhgGIACg/QABgVAUgJIAIAAIABgBQBiAQAFBhIAAAGQgfASgbAAQgrAAgigrgAk3hHQgCgxAUgsQAIgSAOgFIAaACQBDAygdBSQgEANgLAGIgMABQguAAgfgmgApAhrIAAgaQAKgUAYgFIAEgCQBDALgBBBIgBAGQgTAJgSAAQglAAgdgmgAjJiVQgCgKACgJIAAgTQAGgGAIgCIAJgGQA1ANAMA0IAAAGIgHAMIgFAEIgOABQgoAAgWgkgAiylbQghhEBVgSIAagIIADgIIABgFIAAgGQAfgxA8ATIALAMIAMAHIAGgGIARgTQgHhSBLgbIAZgLIACgGIAEgFIAXgGQBWAMgGBVIAAAGQBIArgIBZQgFAxgyAJQguAIgegmQgEgJABgKQACgOAHgLIgGgaQgzATg7gbQgUAMgYAHQgCAagGAYQgGASgQAIQAIA1gdAwQgJAOgQAJQh+AAACh2g");
	this.shape_10.setTransform(418.1,64);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#78460E").s().p("AHoJKIAAgTIATgfIANgFQAaAHASAVIAEAGIgDATIgBAGQgGAMgLAHIgZACQgTgKgPgPgApJF4IAAgTQANgWAfAAIAAgBQAZgBALAVIAEAHQgNAsgYAAQgUAAgbgdgAinDGQgHgQgBgTQgDhSBPgdQAAg4ApgqQAZgaAhABQCKgHABB/QAAANgEANQAmAlgEA6QgCAmggAXIgDABIgUABIAJgVIgBAAQg0Ahg+gTIgMgCIgIANIgDAGQglAUgeAAQg1AAgehBgAIogFQg2gDAKg4QACgNAHgKIADgCIAIgBIAAgCQBVANgoA/QgHALgNAAIgBAAgAmUhCQgKgPAAgRIgBgZIAKgNIADgGIAKgFIABgBQBUARg4A8QgKALgMAAQgJAAgKgGgAkpkfQgxhkBNhIQAKgJAPgEIAdgLQAqgLAUAiIADAGIABAHIgDAZIgEANIgTAMQgMAIgJALQAcAlgKAuQgFAYgXALQgQAFgOAAQglAAgYgggACBmiIgFgGQgHgbAOgYIAGgMQAHgOAQACIAAgBQA6AfggA3IgFAHIgmACgAgZnzQgSgDgIgPQgDgeAQgYQAMgTASgPIARgCIAIABQAIABAAgEQAkgFAbAWIAHAGQgHBZhWAAQgLAAgQgCg");
	this.shape_11.setTransform(429.4,62.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#78460E").s().p("AjsFtIgEgFQgegFgPgYQgIgOADgSIgJgMQgGguAeggQASgUAaAKIAOAEQAAgXAPgPQAYgaAhgGQBpgJAABbQAAAjgXAcIADAGIAUAUIAEAGIABAGIgBANIALATQgIAfgiAHQgYAFgUgQIgEgGIgDgHQgeAegfAAQgcAAgdgbgAGBC6IgDgHIgBgMIAAgHQAEgLALgGIAOgIIAbAKIAHAFQAFANgFAMQgDAKgKAHQgJAEgJAAQgPAAgNgKgAm+ibQAAgRAHgRQAIgVALgVQAMgWAVgHIATACQAiAZgNAmIgEAMIgIAHIgJAMQAdAfgSAmIgHAUQgMACgKAAQg+AAAChSgAiPlMQgEgMAEgNQAHgVAOgNIAdACIAZATQAJAIAEALIgDAMQgHAQgRAIIgPABQgbAAgTgSg");
	this.shape_12.setTransform(441.6,39.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#78460E").s().p("ABYEdIgPgNIgBgGIgBgTIgCABIgbgBQgSgMgEgUIgEgfQAPgbAegKIAVgFIAJgPQALgRAQgEQBdAGgpBPIgMAaIACAGIAIANIABAHIgBAMQgKAPgOAIQgMAHgPACgAizjYQgEgJACgKIACgNIARgTQgCgGADgFIADgIQArAKgMAzIgCAHIgEAFIgIAHIgaACg");
	this.shape_13.setTransform(414.5,44.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(256.7,68.9,193.9,98.8);


(lib.shape34 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFDF18").s().p("AA+CSIgggFIh1AIIgQgDQAJgfACghIACgzQADgWAMgIQAOgIAjAAQAYAAAJAWQAFAJADAOIAMBHIAQgkQAHgNAHAAQAJAAANAbIARAnQADgJAAgSQAAgJgEgRIgFgZIgqgLQgegJgFgQQgHgOgSgVQgYgYgQAAIgTAFIgPAGIgXAAIgEgYIgDgNIAEAAIADgBIADgCQAOgtAugeQgBASATANQAVAQAFALQAMAnAFAJQAMAPAXAAQAYAAAfgWQAigZABghIAMAOQAEAFAAAIQAAAhggANQgfAMAAAkIADAJQAEAFAHAAIAYgIQAKAUAEAdIAEAfIgBARIABAAQgdAmggAAgAiQAXQgLgHAAgLQAAgFAGgNQAGgOAGAAQADAAAGAFIAIAGIADAIQAFAIAAAHQAAAFgGAIQgFAIgGAAQgFAAgKgFg");
	this.shape.setTransform(-47.5,76.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E78A0E").s().p("AmLFaQgPgOAAgfQAAgdAKgZQALgbADg7QACg3AigHIAagEQANgEAFgPIADgcQADgUAJgHQACgCAXgHQAUgFAAgGQACgYAYgTQAYgSAAgZQgBgpALgVQASgfAvAAQArAAAIAIQAJAJAAAuIAAAIIgDASQgEAWgIAHIAAgDQAEgZgHgUQgIgYgSAAQgtAAgDAdQgGAxgUAWIg0A2QgTAXgZAlIAAAtIgDAAIACANIAEAYIAXAAIAQgGIATgFQAQAAAXAYQAVAVAGAQQAGAQAdAJIArALIAEAZQAEARABAJQAAASgEAJIgQgnQgNgbgKAAQgHAAgGANIgQAkIgNhHQgCgOgFgJQgMgYgXAAQgjAAgPAKQgMAIgCAWIgDAzQgCAhgJAfIgBAFIgBAAIhPAHQghAAgPgOgAk4C7QgFAOgBAGQAAALAMAHQAJAFAFAAQAGAAAGgIQAFgIAAgFQAAgJgEgIIgEgIIgIgGQgFgFgEAAQgFAAgHAOgADIEmIgmgYQgYgRgVAGQAKgQAHgDIAZgBQAxAAAVA0IgDABIAAACgAGFCjIgCgNIgRADIgPADQgEAAgWgKQgXgLgCgFQAJgFALgMQAIgJAIAAIAnAGQAgAHgBAHQAAAPgUAogADhCsIgIgCIADgRIAbAAIAAAKQAAAKgNAAgAD3BvIACgEQADgDAHgBIACgBIAFgBIAJAAQAEACAAAIQAAAIgEACIgMADQgQAAAAgNgADXhYQgUgVgfAAIgoAHIgZAHQgGAAgMgVQgNgVAAgHIASAIQARAHAGAAQAHAAARgLQARgMAQAAIAmADQAYABANgCQAagEAggaQAlgdACgeIAEAAQABAJAEAGQAGAHAIgBIACgDIABgGIgIglIgJgpQAgAPAJAMQAHAMABAdQgBAPgGAbIgHAcIgCAFIgCADQgSASgvAhQg8AqgPAAgAEklaQAAgKADgDQAJAAADADQgHABAHABIALABQACAIgEAGQgEAGgKAAQgKAAAAgNg");
	this.shape_1.setTransform(-31.2,56.2);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-72.3,20.2,82.2,72.1);


(lib.shape33 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFDF18").s().p("AB+BLQgXgKg9AAIhKAGIg5AFIgXgRQgegaAAgcIADgPIACgVIAVAAQAGAIANAZQAFgNAcgdIAngoQgGARAXAkQAXAmAgAAIAigIIAggFIAVACIABApQACAdAGALg");
	this.shape.setTransform(-52.5,82.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E78A0E").s().p("AhrFyQgFgLgCgdIgBgqIgVgDIggAHIgjAIQgfAAgagoQgWgkAGgRIgnAoQgdAdgEAPQgNgbgHgIIgUAAIgCAVIgDARQAAAcAeAaIgDASQgegCgggPQgogVAAgeQAAgbAjgyIA2hKIABAjQACARANAAQA1AAAgg0IAZgvQAQgdAPgQIAEADIAAAvQgHAhAAAPQAAAYASAhQAVAmAWAAQAVAAATgTIApghIACADIAHAeQAFATAAANIgDAeQACAcAQAAQAnAABSg/IAXgRQAPgHATAFQAXAFArgoIAAAaIgYAaIgYAWIAAAAIgBAAIgBAAQgBAAgBAAQgBABAAAAQAAAAAAAAQAAABAAAAIhqAzQhcAtgMAAgAGHD4IgJgHIgDgDQABgGAGgEQAIgFAMgBIAQAJIgCARgAGpDNQAEgSAHgHQAFgHANAAIADAAIAMADIAAAUIgLAJIgHACgADeCpQgMgQgNAAIgoAGQgXAAgdgXQAjgGAmgxQAigtAmAAQAVAAAOArQALAjAAAoQABAQgUAJIgVAFQgYAAgKgPgAg2CmQgGgFgPgiIAAgiIADAAQAMAdAoABIAWAEQAKAFAAASQAAAIgCADIAAACQgMAKgSAAQgbAAgHgHgAi7AbIAdgbQAOgMAMAAQAFAAAMAIIAPAFIAGgBQAEAYgYAAIgegEQgJAAgiAVgABfgDIA0g6IA5g5QAYgegBgqIgBgTQgDgbgPgXQgNgUgegcIAKgMQAPAAAlAXIAhAXIAIgBIADgCIAAgRIgfhHIABAAQAzAMAVArQAPAgAAA5QAAA8hUBFQgnAhhqA8gADxjiIABAPIACAKQAFALALAAQAOAAACgGQgBgMAEgKIAGAFIgDgGIgDABIAAAAIgRgPQgKgKgEgKQgHAGAAAVgAGtkwQgDgEgBgRIABgOQADgMAOAAQAKAAAEAHIAFAIIABADIAAAOQgBANgIAEIgIABgAAsljIgDgBQgCgRAOAAIAcADIAAAGIgKAGIgTAFg");
	this.shape_1.setTransform(-27.3,53.9);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-74.3,16.5,93.9,74.9);


(lib.shape32 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFDF18").s().p("AhCCcQgUgOgMAAIABgHIAFAAIAlgGQAbgHAFgHIAAgTIgygIQgmgIAAgZQAAgaBNgdQBAgZAWgBIACAFQgqAKgaARIgKAHQgbAUAAAWQAAAPAJACIAVAAQA0AAAwgoQArgjAAghQAAgLgLgCIgVAAIgiADIBQg0QAwgcAkAAQALgBAFAVQADAMAAAMQAAATg8AyQhJA5gKAPQgVAbhwBUQgKAAgTgOgAjuhhQAAgiA3geIAQgIIAdALIAgAIQgFALgKAHIgLADQgSAFgaAOQgtAZgOACQgDgDAAgLg");
	this.shape.setTransform(-29.4,78.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E18403").s().p("AnVEwQAAgKAGgSIAFgTIAIAAQAIAEARAWQANAQAMAAQAJAAAxgxIA1g1IASAAQAAAQAGAiQAJAsALAAQAKAAASgMQAWgOAJgRQABATAIAqIAOA2QgHAJgKACIgdAAIhPgGQgVAAgiAMQgjAMgUAAQhHAAAAhYgAFTDxQgFgFgBgOQgBgKgIgFQgIgFgBgIIAagDQAaAAAIAPIAGgEIAJAAIAAAaQgEAHgOAHIgQAGQgNAAgEgHgAhdCeIAFgRIADgPQAAgNgXgJQgQgGgMAAIgHABQAKgHAFgLIgggIIgdgLQAlgSAeAAQAYAAATARQAUATAAAYQAAAWgNAUIgdAtQAAgKAIgXgACMAdQBLhRAAhEQAAhmghg7Qgeg1hBghIAEgJQBmAEAtAtQAuAuAABnQAADJjbBQQApgkAigmgAgdgYQgGgVgVgSIgjgaIgfgdQAHgMAQgEIAUgBQAXAAAdARQAhAVAAAbQAAARgGAWQgHAbgMAEIADAEQgHgGgGgWgAGpgdQgKgEAAgOQAAgZAcACQAbADAAAUIgCAMQgGAJgVAAgAGVjVQgBgGABgFQACgJANAAQAVAAgJAWQgHAUgPAEgAGTkbQgMgRgVgCIAEgOIApgGIAgACQAKAEAGAYQgPAZgTAAQgMAAgOgQgAiglQIAAgFIAcgNIAbgMIAAABQALAAAKAGQgDANgNAFIgZAFgAgblmIgLgBIAAgRQAEgBANgHQALgHAJAAIAGACIAFABIgCAKQgBALgCAEQgFAHgPAAg");
	this.shape_1.setTransform(-27.2,54.8);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-74.3,15.6,94.1,79.6);


(lib.shape31 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFDF18").s().p("Ag4EmQgPgKAAgIQAAgOANgRQATgYAEgIQgFAIgNAGQgMAGgHAAIgIgDQgGgDAAgHIAEgLQAFgIAAgFQAAgLgXgHQgYgIAAgPIADgPIAEgKIAFgEQAqgqAYgmQArhAAAhEQAAhLgWgwIgHgMIAAgVIAAgZIAJgTQAKgQAJAAIAQAEIASANQBfBIAABMQAABQg9BPQgwA/hMA5IAAAWIA3AAIAdgDQgNASgRAqQgSApgOASIAAATIAJADIgFABQgKAAgMgJg");
	this.shape.setTransform(-16.5,49.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E78A0E").s().p("AktDQQBaiMBPAAQAYAAAKAIQAOALAAAcQAAAqgLAZQgSAogLAwIBCgmQAagNAUgQQAQgPgBgmQgCgmAOgNIANgMIgFAKIgCAQQgBAOAYAIQAXAHAAALQAAAFgFAIIgEALQAAAHAGADIAJADQAGAAAMgFQANgHAGgIQgFAIgTAZQgNAQAAAOQAAAIAPAKQARAMAKgEIASAAQgFASgZAMQgqATgMAIQgYAchbAwQAXgOAegxQAZgtAAgNIAAgJIgEADQgkAXg8AtQgoAgg+AUIgfAAIATgxQAPgkAAgUIgDgeQgFgcgLAAQg5AAgWBSIgMA4QgGAagHgBIgQgCIgQgDQgMAAgMAGIgeALQAghbA/higAi5CVQgIAJAAARQAAAMAGAEIATADQASgBAMgMQAOgNAAgVIgCgQIgeAAQgVAGgIAMgAEBEJQgRgbgjABIAAgXIAcgMIAXgFQAfABAJAHQAMAKAAAcQAAA4glAQQgCgggMgUgAD6B8IAAgUQAHgFAIAAQAJAIACAPIgIACgAEtBOIgKgCIAAgGQAEgJAPgFIAPAFQABAUgNAAgAFigHQAAgLAFgIQAFgFAGgCIACAHIAOALQALAKAAAFIgDAJQgDAJgKAAQgcAAABgZgAivgfQgXgJAAgWQAAgYAggJIAzAAIAIAcQABAJgGAIQgIAJgBAHIgNAEIgMAEgAExiWQgFgGAAgJQgBgIAMgOQAMgNAIgEIgGgKQgDgDAAgHIABgIQACgGAJgDIAAgaQgQAFgUgRQgWgTgOAAIAAgDIAoAAQAyAEAMAwIAHApIAEAVQgQAggGAHQgJAHgVAAQgKAAgIgJgAkgj0QA0hDBJgpQBPgtBSAAQBGAABLAvIgDAGQgJgBgKARIgJASIAAAZIgOAAQgug5hkAAQgrAAhCAaQhJAdg4Atg");
	this.shape_1.setTransform(-31.1,54.2);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-70.8,14.4,79.5,79.6);


(lib.shape30 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFBAA").s().p("AhLCFQgMgaAAgUQAAgnCvjOIgyBbQg1BkAAAMQAAANAGAOQAGANAAANQAAAGgGAYIgFAWIgBAFQgIAFgGABIgUABQgNAAgNgdgAhRhvQgGgKAAgRIADgOQAFgJAIAAIAIABIADAAQADADgCAPIAEAIQAGALAAAEIAAAKQgCAJgLAAQgMAAgHgLg");
	this.shape.setTransform(-24.5,49);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E5A90A").s().p("Ah9CcIgOgBIgIgRIgFgYQAAgLADgJIACgDQAIgSAVgKQAjgRAAgJIgDggQABgcAQAAQARAAAAAXQAAALgKAEQgKAEAAATIAAAAQAAAcAOAKQAMAIAgAAIADAAIABAAQAXgCBOgZIAWgIQgCAGgLAKIgBABIgEADQgPANgKAFQgZAKgcAEIgZgBIAAgBIAAgBIgDAAIgEAAIgngBQgRgDgMgNIgDADIgaAAIgTAOIgBAVIACAQQAEAKAJALgABohlIAAgRQAFgFADgOIADgQQgCAMAMAKQAMAJAQgBIgaAWgAB0ibIgBACIABgCg");
	this.shape_1.setTransform(-49.8,76.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFDF18").s().p("Ai9FjIgCgQIACgVIATgPIAZAAIAEgCQALANASADIAnABIAEAAIACAAIAAABIABABIAbABQAcgEAWgLQAKgEAQgNIAEgDIABgBQALgLABgFIgVAHQhMAagaABIAAAAIgEAAQgfABgMgJQgPgKAAgbIAAAAQAAgTALgEQAKgEAAgOQAAgWgRAAQgRAAAAAeIACAgQAAAJgiARQgWAJgIATIgBADQgEAJAAALIAFAXIAJASIgwgJQgpgLAAgSQAAgfBChhQBDhiAYAAQAZAAAHAWQAEAMACAmQACAjAHAOQAMAXAfAAQAWAAAWgOQAdgRAAgZQAAgTgSgRQgRgRgXADIAAgEQAjgDADgnQgEgvAEgUQADgPAdgqQAZgnAAgZQAAhMgagvQghg8hFAAQhAAAgmAXQgrAZAAAxIADAcIACAhIgdgnQgCgGAAgnQAAgzA0g9QA8hFBLAAQARAABBAQQBCAQAKAGQARAJAIAJQANANAAAXQAAAKAIAWQAJAaAIAAQAWAAARgPQAQgOANAAQAnAAAAAfIgFAJQiwDPAAAmQAAAUALAaQANAcANABIAUgBQAGgBAJgGIAZARIAGAGQgzAHgRANQgPAMgEAZIgCAVIACAIIABAHQAGgYAIgJQAHgGAPAAQAJAAAHALQAFALAAAKQAAAYgNAMQgNAMgVAAQgHAAgLgNIgMgQIgKASQgHARAAAJIAEAaQAFAOAAAMQAAAWgNALIgOALIgZgHIgugMQgXAAhAAOIhVAPQgKgLgEgKgAA1BRQgDAOgFAEIAAASIAXAAIAbgWQgRABgMgJQgLgKACgMIAAgCIAAACgABtjQIgDAOQAAARAGAJQAGAMAMAAQALAAACgJIAAgKQAAgFgGgKIgDgJQACgOgEgDIgDgBIgHAAQgJAAgEAJg");
	this.shape_2.setTransform(-43.9,54.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#E18403").s().p("AisELIAOgLQANgLAAgWQgBgMgEgOIgEgaQgBgJAIgRIAKgSIAMAQQAKANAIAAQAUAAAOgMQANgMAAgYQAAgKgFgLQgHgLgJAAQgPAAgHAGQgIAJgGAYIgBgHIgCgIIACgVQAEgZAPgMQAQgNA0gHIACABQASAPADAOQAIAegGAXQABAHAnABIAjgCQAMgDAdgVQAAAfgxAVQg5ATgOAJQgIAEgfAnQgXAcgiAOIADAHQgPAPgYAAgABRAxIgCgDQAAgOAHgKQAHgOAOAEIAAADIgEAUQgEAOgMABgACdgNQAAgkgbgSQgcgTAAgiIADgYQAFgOAQAAQAJAAATAoQATArAAAeQAAARgEASgABBjVQgYgOABgSQAAgOAIgIQAHgFAMAAQAbAAAAAtIgDAoQgCgJgagRg");
	this.shape_3.setTransform(-19.7,64.6);

	this.addChild(this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-72.6,17.1,70.4,75.2);


(lib.shape29 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFBAA").s().p("AhbFIQgGgOAAgTQAAgSADgGQAMAAAQAPIAXgIIAigDQAJgBAOgQQAQgTAJgaIAIAMQABAFAAAPQAAAVgGAYQgFAWgHALIgFAAIhGAIgAAMkBIgYg1IgCgFQAAgNAIgCIALAAQANAAAlASIArAXQgZABgPAPQgOAOAAARQAAAPAGAdIAAADQgIgHgeg3g");
	this.shape.setTransform(-42.6,60.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFDF18").s().p("Ai2FgIAAgEQgCgsgUgXQgVgZAAgHQAAgNAKAAQAMAAAjAYQAjAZALAAQAkAABJg1IAggaIAhgaIBHg1IANAEIAOAEQAKAAALgMQALgNAOAAIALAAQAHABADACIAEAAQAFAFAAAKQAAARgeAHIhCAKQgwAIgYASQgYATAAAeIAGAxQAAAZgSAlIgHABIgBABIgCAAIgBAAIgXAFQAHgMAFgVQAEgZAAgUQAAgQgCgEIgFgNQgJAbgQASQgPARgLAAIghADIgXAJQgQgPgMAAQgDAGAAASQAAATAGANgABvBRQgLgCAAgLIADgKIADgMQgPgDgRgSQgSgVAAgQIAGgZIAHgYQAHANAfAeIAeAaQAAAHgFAGQgHAGAAAGIAhAHQAVAGABAMQgGAKgSAHIgdAGgAgli6IgghYIAAAAIgKgeIgaAAIgHAHIgCAKQABAIAFASIAAAOQgIgEgKgUQgLgTABgIQgBgMAPgXQARgZAQAAQAFAAB5A8QAvAWAdAYQAVASALATIABADIgBAAIgegHIgjgEQgUAAgUARQgXASgBAaIAAABQAAARAMAvQgigUgfhFgAg7kcIADAGIAaA1QAdA3AHAHIAAgDQgGgdAAgPQAAgRAOgOQAOgPAZgBIgrgXQgigSgNAAIgNAAQgJACAAAMg");
	this.shape_1.setTransform(-38.1,57.7);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#E18403").s().p("Ak8FsIAAhIQADgdAjgbQAggZAWAAQAIAAAjAPQAjAPAJAAQAcAAAlgPQAxgUAAgeQAAgJgGgHQgHgJgOAAQgJAAgaAJIghAJQgfAAgagMQgigQAAgdIAFgjQAGgdAAgNIgBgWQgDgLgNgPIADAAIAoARQAaAPAIAVQAFANAEAoQAFAgAUAAQANAAATgIQAUgKAAgKQAAgSgLgYIgOghQgEgQgXgGQgVgHgCgUQgDgngqgvQgogrgXAAIgGAAIgDACQAGAYADAcIAHA5IgVgeIgYgkQgogzAAgWQAAheBRg2QBIgxBuAAQBuAAAuAyQAdAhA1BoQALASAIAwQAJAwALASIAzAtQAnAfAAAZQAAAcgTAXIgTAVIAFARQAEARAAAKQAAA4gPAUQgRAWg/AWQguAQgnAbIhGAxIABAFIgnAIQASglAAgYIgGgxQAAgeAYgTQAYgTAwgHIBCgKQAegHAAgRQAAgKgFgGIgDAAQgEgCgHAAIgLgBQgOAAgKANQgLANgLAAIgOgEIgNgEIhHA1IgfAaIgiAaQhJA0gkAAQgLAAgjgYQgjgZgLAAQgLAAAAANQAAAHAWAaQATAWACAsIgQACgAApgEIgGAXQAAASASAUQAQATAPADIgDALIgDALQAAALALABIAQAAIAdgFQATgHAFgKQAAgNgWgFIgggIQAAgFAGgGQAGgGAAgIIgegcQgggcgHgMgABoh1QgRAOAAAXQAAAlA+ApIBUAsQABgRgLgeQgKgdgMgUQgRglgJgOQgPgYgWAAQgUAAgOAMgAAGhBQgJguAAgRIAAgBQAAgaAVgTQAUgRAUAAIAjAFIAeAGIACAAIgCgCQgLgUgVgSQgdgYgvgWQh5g8gFAAQgQAAgQAaQgPAWAAAMQAAAIAKATQAKAVAJAEIAAgOQgGgSAAgIIABgKIAHgIIAaAAIALAeIAAABIAfBXQAfBFAiAUIAAAAg");
	this.shape_2.setTransform(-36,54.4);

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-67.7,16.2,63.5,77.8);


(lib.shape28 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFBAA").s().p("AheEjIgCACIgTgCIAsgXIASgJIAAAAIAHgEIAAAAQAggQAIAAQAFAAABADIAEAFIAAAMQAAANgKAPIgFAFIhTACgAAZDyIgFgEIgBgEIATgYQAMgQAAgLIgDgVIgBgDIgCgNIgCgQQAAgRAcgBQANAAARAaQAQAZAAARQAAAXgZAZQgYAWgRABQgNAAgMgJgAgwjDQgrglAAgRQAAgNAogQQAkgPAPAAQANAAAkAOIAYAJQgjABgaAgQgcAnARArIAAAFg");
	this.shape.setTransform(-40.1,62);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFDF18").s().p("AgZE1QAMgPAAgNIAAgMIgEgFQgDgDgFAAQgIAAggAQIAAAAIgHAEIAAAAIgSAJIgsAXQgWgBgugBIAAAAQBFgVA1gYIAIgDQArgVAWgTQAVgTAAgSIgDgOIgHgaQgHgcACgGQA8gKAlAfQAhAdAAAxQAAAVgMAXIgMAZIgwAfIg7ACIgcABgAAXCYIACAQIACANIABADIADAVQAAALgMAQIgTAYIABAEIAFAEQAMAJANAAQARgBAYgWQAZgZAAgXQAAgRgQgZQgRgagNAAQgcABAAARgACNBDQgmggAAgNIADgWQAEgHAOAAQAQAAAaAYQAdAdAAAXIgBANQgBAHgHAIIgIAIQgLgOgagYgAgBhPQgegjgZgSQglgbgrAAQgqAAgMAbQgHANgFA/QgFgDgLgfQgKgeAMg2QAMg4BNgqQBMgqBLAAQAXAAAZAMIAwAUQAYAIAQAbIARAfIAEALIAAAuQgLgQgRgNQgRgMgHADQgDgFgegHQgcgHgSAAQgdAAgJAgQgGASAAApIABAmIAPAwQgOgbgJgNgAhGkAQgoAQAAANQAAARArAlIAzAtIAAgFQgTgrAegnQAYggAjgBIgYgJQgigOgOAAQgQAAgkAPgACjhWQAAgOAfgHQAZgFAEATIABAIIAAAMQgDAGgPAAQgrAAAAgTg");
	this.shape_1.setTransform(-38.2,59.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#E18403").s().p("AlCFLQAPgSCBguQB2gqAAgcQAAgSgagQQgngXgMgNIAAgOIAngGQgCgahEhDQhDg/AAgkQAAhvA6g+QBEhLCSAAQBIAAAXAJQAfANAiAyQAFAIADAeQACANAFAJIANAOQAHAFAHAdQAGAcAAARIgDAkQAaAFAZAYQAeAcAAAfQAAA9gKAiQgPAxgpAkIhUBFIgyAkIAMgZQAMgXAAgVQAAgxghgdQgkgfg/AKQgCAGAJAcIAIAaIACAOQAAASgXATQgUATgrAVIgIADQg1AYhEAVIgCAAIgPABIh6ABgAB8AVIgCAWQAAANAlAgQAaAYAMAOIAIgIQAHgIABgHIAAgNQAAgXgcgdQgbgagPAAQgOAAgFAJgAiEgbQAAAcAqA2QAgAoAaAHIAAgEQAQgBAKghQAGgYAAgZQAAgSglgfQgjgdgRAAQgrAAAAAkgADFAAQAAATAqAfIA0AeQgJgugIgUQgPgfglgBQgZABAAARgAAogSIgPgwIgBgmQAAgpAGgSQAKggAcAAQASAAAdAHQAdAHADAFQAHgDASAMQAQANAMAQIAAguIgFgLIgQgfQgRgbgXgIIgxgUQgYgMgXAAQhMAAhMAqQhMAqgMA4QgNA2ALAeQAKAfAFADQAGg/AGgNQANgbApAAQArAAAmAbQAZASAcAjQALANANAbgADUhWQgeAHAAAOQAAATArAAQAPAAACgGIAAgMIAAgIQgDgPgQAAIgLABg");
	this.shape_2.setTransform(-40,57.7);

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-72.3,24.3,64.6,67.2);


(lib.shape27 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFDF18").s().p("AkJEIIgFAAQgHgJAAgFIAKgWQAKgVgBgEQACAJAKALQALAMAIAAQAhAAARgdQALgSAGgkQgaADgWgRQgWgSgCgXQAJgEANgDIATgEQAUAAAcAXQAfAZAyAGIAAgDQgagNAAglQAAgGAGgMQAFgLgCgGIAOAAQASADAKATQAMAVAAAjQAAAWgNAoQgNAlgQAMIgYAEIAGACIABAAIglAGIiAALgAACB3QAAgJAMgMIANgLIAIAEIAMAGQAHADAAADQAAAKgJAIQgJAIgRAAQgRgFAAgFgAB+BEIgSgKQgJgFAAgMQAAgRAJgMQAKgNAQAAIAMABQAJAEgBAHQAAAOgGAUQgJAXgMAAIgBAAgAjIgHQgagQAAgVQAAgSAMgNQANgPAVAAQAIAAARAPQARAQAKASQAcAug2AAQgWAAgYgMgAAFg7IgxgtQgjgeAAgmQAAgkA6gdQAwgaAxAAQAUAAAVAYIAXAYIgGAFIgkgDQhdAAAABdQAAAVALAcIACAGIAPAmgAC6ieIAAgVQAAgUAGgJQAIgLAUAAQAbAAAOALQAMAJAFAUQgNgEgEAIQgGAKgFAAIgMgDIgOgDQgQAAgDAIIgIAeg");
	this.shape.setTransform(-29.5,66.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E18403").s().p("AkoFgIhSgDQAPgdAvgWQAkgQAAgmQAAgoAQgmQAUgwAkgSIgGgSQgGgPAAgIQAAghAOgjQAVgyAiAGQgOgiAggjQAbgeAkgKQAPgEADgXQAEgdAGgHQATgVASgFIAhACIAAgRQgHgNgSgLQgSgNgQAAQgXAAgTANQgMAIgGALQgIALgCAOIgEAAIAAglQANglAHgLQAPgXAeAAQAmAAAYAXIAgAoIAAAfIAQgEQAIgFAJAAQALAAAgAKQAgAKAPAAIAyACQAeAGAKAYQARAnAvAoQAiAcAAA+QgBASgJAIQgLAJAAAPQALABAMANQALANAAAMQABAZgUAQQgOANgeALIgMAoIgHAVQgFALgFAFQgUAVg2APQg6APgugIQAOAmg4AiQgiAVg7ANQARgMAKgkQAOgoAAgWQAAgjgMgVQgJgUgSgDIgNAAQACAGgGALQgFAMAAAHQAAAkAaAOIAAADQgygHgfgZQgcgWgVAAIgTADQgNADgIAFQACAXAVARQAWASAbgDQgHAkgKASQgRAdgiAAQgIAAgLgMQgKgMgBgIQAAAEgJAVIgKAVQgBAGAIAIgAA2C9QgMAMAAAKQABAFARAEQAQAAAKgIQAJgHAAgLQAAgCgIgEIgLgFIgIgEgACVBnQgJANAAARQAAALAJAFIASALQAMABAJgZQAHgTAAgOQAAgHgJgFIgLgDQgRAAgJAPgAitAOQgNANAAASQAAAVAaAQQAYAPAWAAQA3AAgdgxQgJgSgSgQQgQgOgIAAQgVAAgNAOgAARiRQg4AdABAjQAAAmAjAfIAwAqIAdAgIgPgmIgCgFQgMgbAAgVQAAhdBeAAIAkADIAFgEIgWgZQgVgXgVAAQgwAAgzAagADoh1QgFAJgBAUIABAWIALAYIAIgeQADgHAQAAIANADIANADQAEAAAHgLQAEgIANAEQgFgTgMgJQgOgMgcAAQgUAAgIALg");
	this.shape_1.setTransform(-33.5,57.3);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-71.4,21.7,75.8,71.1);


(lib.Символ39 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ40();

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:0.94,scaleY:0.94},5,cjs.Ease.get(-1)).to({scaleX:0.86,scaleY:0.86},7,cjs.Ease.get(1)).to({scaleX:0.93,scaleY:0.93},6,cjs.Ease.get(-1)).to({scaleX:1,scaleY:1},6,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-162.2,-16,324,34);


(lib.Символ37 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Символ 38
	this.instance = new lib.Символ38();
	this.instance.setTransform(10.2,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(18).to({scaleX:1.14,scaleY:1.14,x:12.5},9,cjs.Ease.get(-1)).to({scaleX:1,scaleY:1,x:10.2},10,cjs.Ease.get(1)).wait(13));

	// Символ 38
	this.instance_1 = new lib.Символ38();
	this.instance_1.setTransform(-4.6,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(9).to({scaleX:1.14,scaleY:1.14,x:-4.5},9,cjs.Ease.get(-1)).to({scaleX:1,scaleY:1,x:-4.6},10,cjs.Ease.get(1)).wait(22));

	// Символ 38
	this.instance_2 = new lib.Символ38();
	this.instance_2.setTransform(-21.3,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({scaleX:1.14,scaleY:1.14,x:-23.5},9,cjs.Ease.get(-1)).to({scaleX:1,scaleY:1,x:-21.3},10,cjs.Ease.get(1)).wait(31));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-43.8,-24.9,76.5,50);


(lib.Символ29 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ27();

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:360},44).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-16,-16,32,32);


(lib.Символ28 = function() {
	this.initialize();

	// Слой 2
	this.instance = new lib.Символ29();
	this.instance.setTransform(0.1,-0.2);

	// Слой 1 - копия
	this.instance_1 = new lib.pric();
	this.instance_1.setTransform(-51.3,-51.1);

	this.addChild(this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-51.3,-51.1,102,103);


(lib.Символ23 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ24();
	this.instance.setTransform(286,-26.2);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:-801},299).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(147.7,-108.4,446,153);


(lib.Символ22 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.Символ21();
	this.instance.setTransform(636,0.1,1,1,0,0,0,1,0.1);

	this.instance_1 = new lib.Символ21();
	this.instance_1.setTransform(-5,0.1,1,1,0,0,180,1,0.1);

	this.instance_2 = new lib.Символ21();
	this.instance_2.setTransform(-634,0.1,1,1,0,0,0,1,0.1);

	this.addChild(this.instance_2,this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-955.5,-45.2,1911,90);


(lib.Символ20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ22();
	this.instance.setTransform(635.1,0.1,1,1,0,0,0,1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:-634.9},70).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-321.4,-45.2,1911,90);


(lib.Символ10 = function() {
	this.initialize();

	// Слой 1
	this.instance = new lib.Символ11();
	this.instance.setTransform(0,30.3);
	this.instance.alpha = 0.148;

	this.addChild(this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-104.5,22.3,209,16);


(lib.Символ2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 6
	this.instance = new lib.Символ5();
	this.instance.setTransform(-29,-64.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:-11.8,y:-55.9},4,cjs.Ease.get(-1)).to({x:11,y:-44.5},5,cjs.Ease.get(1)).to({x:-7.6,y:-53.8},5,cjs.Ease.get(-1)).to({x:-29,y:-64.5},5,cjs.Ease.get(1)).wait(1));

	// Слой 7
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#121410").s().p("AhaimIFYCmQjJBAkyBnQBAjwBjhdg");
	this.shape.setTransform(23.8,-13.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#121410").s().p("AhtidQBzAgBmAwICTBKIgMADQjIBEkpBaQA6jbBXhgg");
	this.shape_1.setTransform(23.8,-12.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#121410").s().p("AhrifQBuArBvAsICPBTIgHAGQjOBSksA9QA7jfBahgg");
	this.shape_2.setTransform(24,-12.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#121410").s().p("AhoiiQBoA8B9AoICHBjIAAAIQjXBpkwANQA9jnBeheg");
	this.shape_3.setTransform(24.3,-13);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#121410").s().p("AkMCfQBAjwBjhdQBIBOCnAoICICFQijBijMAAQhSAAhZgQg");
	this.shape_4.setTransform(25.3,-12.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#121410").s().p("AkUChQBPjlBkhdQBZBHCWAvICICFQjOBIkcAAIhAgBg");
	this.shape_5.setTransform(24.5,-14);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#121410").s().p("AhbidQBlBCCLA0ICHCFQjmAllRAbQBdjeBjhdg");
	this.shape_6.setTransform(23.8,-14.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#121410").s().p("AhWiaQBuA/CBA3ICICFQjoAFlZA1QBmjYBkhdg");
	this.shape_7.setTransform(23.4,-14.7);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#121410").s().p("AhUiYQB1A9B7A5ICHCFQjogOldBDQBrjTBjhdg");
	this.shape_8.setTransform(23.1,-14.9);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#121410").s().p("AhTiXIDwB1ICHCFQjogUlfBJQBtjSBjhdg");
	this.shape_9.setTransform(23,-14.9);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#121410").s().p("AhoijQBnBAB/AoICGBnIACAIQjZBukxABIgBABQA+jpBfheg");
	this.shape_10.setTransform(24.5,-13.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#121410").s().p("AhqigQBsAxB0AqICMBaIgEAFQjRBbktArIgBABQA8jiBbhfg");
	this.shape_11.setTransform(24.1,-12.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#121410").s().p("AhsieQBxAmBrAtICQBPIgJAEQjLBMkqBKIgBABQA7jdBYhgg");
	this.shape_12.setTransform(23.9,-12.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#121410").s().p("AhtidQBzAgBlAvICUBKIgNADQjGBBkoBdIgCABQA6jaBXhhg");
	this.shape_13.setTransform(23.8,-12.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape}]},1).wait(1));

	// Слой 3
	this.instance_1 = new lib.Символ4();
	this.instance_1.setTransform(24.5,-6.4,1,1,0,0,0,-41,-11.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({scaleX:1,scaleY:1,rotation:69.2,x:25.4,y:-6.5},4,cjs.Ease.get(-1)).to({regX:-41.1,scaleX:1,scaleY:1,rotation:161.2,x:26.5,y:-6.4},5,cjs.Ease.get(1)).to({regX:-41,rotation:86,x:25.6},5,cjs.Ease.get(-1)).to({rotation:0,x:24.5},5,cjs.Ease.get(1)).wait(1));

	// Слой 2
	this.instance_2 = new lib.Символ3();
	this.instance_2.setTransform(41,-108.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_2).to({rotation:10.2,x:39,y:-104.4},4,cjs.Ease.get(-1)).to({rotation:0,x:41,y:-108.4},5,cjs.Ease.get(1)).to({rotation:10.2,x:39,y:-104.4},5,cjs.Ease.get(-1)).to({rotation:0,x:41,y:-108.4},5,cjs.Ease.get(1)).wait(1));

	// Слой 8
	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.lf(["#F71F18","#7A191F"],[0,1],-72.4,0,72.4,0).s().p("AAYApQkQh4j9BvQj9BwAkgbQAlgcC1iaQASgQAUgNQAQgKAQgJQCmhWD4BhQD2BhDAAlIA4AKIAbAFQDbAfAAAhQAAAhjVAKIggAAQjJAAj+hxg");
	this.shape_14.setTransform(-67.4,-73.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.lf(["#F71F18","#7A191F"],[0,1],-72.4,0,72.4,0).s().p("AGmCQQjAgnj2hhQj4hfimBWQgQAHgQAKIgnAQQj9BwAkgbQAlgcC0iaQC1icEwB3QEuB1DbAgQDbAfAAAhQAAAhjVAKIghABIg4gLg");
	this.shape_15.setTransform(-67.4,-84.6);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.lf(["#F71F18","#7A191F"],[0,1],-52.7,4.8,55.9,-2.3).s().p("AG1CdQi/gnj2hhQj5hgiaBPIgZAQQgXAHhKAcQkGBuA9giQA8gjDjioQDjiqEACIQECCGDbAfQDaAgAAAhQAAAhjVAJIghABIg4gKg");
	this.shape_16.setTransform(-69,-85.9);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.lf(["#F71F18","#7A191F"],[0,1],-53.6,1.8,55,-5.3).s().p("ArVCpQAkgfCrigQAwg3AhgsIAZgQQCbhQD4BhQD2BhDAAlIA4ALQD2AjAAAhQAAAhjVAPQjUAOkIhvQkHhukOCEQjbBsgSAAQgEAAAHgFg");
	this.shape_17.setTransform(-68.1,-71.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.lf(["#F71F18","#7A191F"],[0,1],-33,9.7,39.4,-4.6).s().p("AHFCqQi/gnj4hhQj3hgiPBJIgSANQgZAGiBAwQkPBtBVgqQBVgqEQi1QEQi4DTCYQDUCXDbAfQDaAgAAAhQAAAhjVAJIghABIg4gKg");
	this.shape_18.setTransform(-70.6,-87.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.lf(["#F71F18","#7A191F"],[0,1],-34.8,1.9,37.6,-12.4).s().p("ArcDMQAkgjChinQBOhdAthKIASgMQCQhLD4BhQD2BhDAAnIA4ALQD2AhAAAhQAAAhjUAUQjUATj/hlQj9hikfCZQjsB/gSAAQgEAAAHgHg");
	this.shape_19.setTransform(-68.8,-68.1);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.lf(["#F71F18","#7A191F"],[0,1],-13.2,14.5,23,-7).s().p("AHXC2QjAgnj4hhQj2hfiFBDIgLAKQgcAGi3BDQkYBqBtgwQBtgxE+jDQE9jGCmCpQCmCnDbAgQDbAfAAAhQAAAhjVAKIghABIg4gLg");
	this.shape_20.setTransform(-72.3,-88.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.lf(["#F71F18","#7A191F"],[0,1],-16,2.1,20.2,-19.4).s().p("ArkDwQAkgmCXisQBsiFA6hoIALgKQCFhFD2BhQD4BhDAAnIA4ALQD2AjAAAfQAAAhjTAYQjTAZj2haQjzhYkxCuQj7CRgUAAQgEAAAGgHg");
	this.shape_21.setTransform(-69.5,-64.7);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.lf(["#F71F18","#7A191F"],[0,1],2.8,2.3,2.8,-26.4).s().p("ArrEUQAjgpCNiyQCKitBHiHIAEgGQB6g/D2BhQD4BhDAAnIA4AKIAbAFQDbAfAAAhQAAAfjTAdQjSAdjshPQjqhNlCDDQkKCjgWAAQgEAAAGgHg");
	this.shape_22.setTransform(-70.2,-61.3);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.lf(["#F71F18","#7A191F"],[0,1],6.7,19.4,6.7,-9.3).s().p("AHpDDQjAgnj4hhQj2hfh6A9IgEAHQgeAFjvBXQkhBpCGg4QCFg3FsjSQFqjUB5C6QB4C4DbAgQDbAfAAAhQAAAhjVAKIghABIg4gLg");
	this.shape_23.setTransform(-74.1,-89.7);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.lf(["#F71F18","#7A191F"],[0,1],-8.9,15.1,20.1,-7.8).s().p("AIeC+IgCAAIg4gKIgggHIg8gPIgJgCIg9gRQhpgdh2gtIgigNIgcgKIgQgGIgVgIIgXgIQi1g5hpApQgnAKiAAxIgiAOIgpAOIgYAKQkWBoBygyQBOgjC7hzQBfg4B6g8QCchPB6ABQCEgGBIBYQB6COCxAnQAWAFAXADQCxAaAbAcQACAmh1AOIgTABIhEABIgdAAg");
	this.shape_24.setTransform(-73,-88);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.lf(["#F71F18","#7A191F"],[0,1],-11.6,1.9,17.3,-21.1).s().p("ArgD1QAjgnCRiqIAVgZIAhglIAYgcQBXhmBBhKQBVgkB+AdQAqAKAtAOIAYAIIANAGIAdALIAiANQB2AsBoAeIA+AQIAIADIA9AOIAgAHIA3AKIACAAIALACIAXADIATAEQBcAOAoAQQA1AQgPARQgKAXiEAUQgfAFgjAEQjMAWjohSQgTgGgTgFQjhg+kaCeIg5AhQjSB4gTAAQgEAAAGgGg");
	this.shape_25.setTransform(-70.2,-63.8);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.lf(["#F71F18","#7A191F"],[0,1],-24.8,11,33.1,-6.2).s().p("AJzCyIhCgCIgcgBIgDAAIg1gKIglgHQisgmjXhSIgLgEIgDgBIg9gXQisg4htAiQgyAJhwAqIgiAPIgoAPIgXAJQkLBoBegrQBEgiC6h7QBdg+B4gwQCVg+CBAQQB+AGBOBKQCIB4CpAiIAsAIQCxAbAUAdQgEAmhuAQIgTAAg");
	this.shape_26.setTransform(-71.5,-86.5);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.lf(["#F71F18","#7A191F"],[0,1],-26.4,1.5,31.5,-15.7).s().p("ArYDWIABAAQAjgjCUiiIAWgWIAigkIAagaQBZhaBRg0QBXgZB3AgQA1APA4AUIADABIALAEQDXBTCsAlIAlAIIA1AJIADABIAYAEIAXADIASADQBhAPAeASQAoASgdAPQgVAUh5AQQgeAEgjADQjFAOjlhUIgkgMQjlhJkMCJIg5AeQjQBygSAAQgFAAAGgHg");
	this.shape_27.setTransform(-69.9,-66.3);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.lf(["#F71F18","#7A191F"],[0,1],-40.8,7,46.1,-4.4).s().p("AJoCpIhAgEIgagCIgFgBIg0gJIgkgHQiogkjUhQIgUgHIg2gVQikg4hvAZQg+AIhgAnIghAQIgoAQIgWAIQj/BoBKgmQA5gfC5iGQBbhDB2gjQCNguCKAgQB3ASBUA7QCWBjCgAdIArAHQCyAcAOAeQgMAnhmATIgSgCg");
	this.shape_28.setTransform(-70.1,-85.1);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.lf(["#F71F18","#7A191F"],[0,1],-41.4,1.4,45.4,-10.1).s().p("ArSC5IABAAQAiggCZiZIAWgWQASgSASgQIAcgXQBbhMBfgfQBZgNBxAiQArANArAQIAUAHQDUBQCoAkIAkAHIA0AHIAFABIAkAGIAWADIASAEQBmASAUAUQAaASgrAPQgfAPhvAMQgeADghACQi+AHjhhXIgjgMQjphUj+B0QgeANgcAPQjOBpgSAAQgEAAAGgGg");
	this.shape_29.setTransform(-69.4,-69);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.lf(["#F71F18","#7A191F"],[0,1],-56.7,3.5,59.2,-2.2).s().p("AJcCkIg+gHIgegEIgygIIgjgHQimgijPhOIgHgCIgGgDIg8gVQibg6hzAQQhJAHhRAkIggARIgoAQIgUAIQj0BoA2ghQAvgdC3iQQBZhHB1gXQCFgdCUAuQBvAeBaAtQCkBOCYAZIAqAGQCxAcAHAfQgRAohgAVIgSgDg");
	this.shape_30.setTransform(-68.7,-84.2);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.lf(["#F71F18","#7A191F"],[0,1],-56.8,1.3,59.1,-4.4).s().p("ArPCdIABAAQAigdCciPIAXgWQASgRATgOQAPgMAPgJQBehABugJQBbgCBqAlIBMAbIAHADIAGACQDQBOClAgIAjAHIAzAIIA3AJIAVAEIASADQBrAVAJAWQAOASg6ANQgpAMhkAIQgeACggABQi4gBjdhZIghgNQjthfjwBfQgeALgcAOQjMBigSAAQgEAAAGgGg");
	this.shape_31.setTransform(-68.5,-71.9);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.lf(["#F71F18","#7A191F"],[0,1],-72.4,0,72.4,0).s().p("AAYApQkQh4j9BvQj9BwAkgbQAlgcC1iaQASgQAUgNQAQgKAQgJQCmhWD4BhQD2BhDAAlQArAJAoAGQAzAHAnAIIARADQBwAXAAAXQAAAhjVAKIggAAQjJAAj+hxg");
	this.shape_32.setTransform(-67.4,-73.4);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.lf(["#F71F18","#7A191F"],[0,1],-72.4,0.2,72.4,0.2).s().p("AJSCjQgngIgygHQgpgGgrgJQi/gnj2hfQj5hhilBWQgRAIgPAJIgoAQQj9BwAlgcQAkgbC1iaQC1icEwB3QEuB1DbAgQDaAfABAjQAAAihwAeIgSgDg");
	this.shape_33.setTransform(-67.4,-83.5);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.lf(["#F71F18","#7A191F"],[0,1],-73.8,-0.4,73.7,-0.4).s().p("AJcCkIg+gHIgegEIgygIIgjgHQimgijPhOIgHgCIgGgDIg8gVQibg6hzAQQhJAHhRAkIggARIgoAQIgUAIQj0BoA2ghQAvgdC3iQQBZhHB1gXQCFgdCUAuQBvAeBaAtQCkBOCYAZIAqAGQCxAcAHAfQgRAohgAVIgSgDg");
	this.shape_34.setTransform(-68.7,-84.2);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.lf(["#F71F18","#7A191F"],[0,1],-72.4,0.9,73.5,0.9).s().p("ArPCdIABAAQAigdCciPIAXgWQASgRATgOQAPgMAPgJQBehABugJQBbgCBqAlIBMAbIAHADIAGACQDQBOClAgIAjAHIAzAIIA3AJIAVAEIASADQBrAVAJAWQAOASg6ANQgpAMhkAIQgeACggABQi4gBjdhZIghgNQjthfjwBfQgeALgcAOQjMBigSAAQgEAAAGgGg");
	this.shape_35.setTransform(-68.5,-71.9);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.lf(["#F71F18","#7A191F"],[0,1],-75.1,-0.7,75.1,-0.7).s().p("AJoCpIhAgEIgagCIgFgBIg0gJIgkgHQiogkjUhQIgUgHIg2gVQikg4hvAZQg+AIhgAnIghAQIgoAQIgWAIQj/BoBKgmQA5gfC5iGQBbhDB2gjQCNguCKAgQB3ASBUA7QCWBjCgAdIArAHQCyAcAOAeQgMAnhmATIgSgCg");
	this.shape_36.setTransform(-70.1,-85.1);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.lf(["#F71F18","#7A191F"],[0,1],-72.7,0.4,74.4,0.4).s().p("ArSC5IABAAQAiggCZiZIAWgWQASgSASgQIAcgXQBbhMBfgfQBZgNBxAiQArANArAQIAUAHQDUBQCoAkIAkAHIA0AHIAFABIAkAGIAWADIASAEQBmASAUAUQAaASgrAPQgfAPhvAMQgeADghACQi+AHjhhXIgjgMQjphUj+B0QgeANgcAPQjOBpgSAAQgEAAAGgGg");
	this.shape_37.setTransform(-69.4,-69);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.lf(["#F71F18","#7A191F"],[0,1],-76.3,-0.6,76.6,-0.6).s().p("AJzCyIhCgCIgcgBIgDAAIg1gKIglgHQisgmjXhSIgLgEIgDgBIg9gXQisg4htAiQgyAJhwAqIgiAPIgoAPIgXAJQkLBoBegrQBEgiC6h7QBdg+B4gwQCVg+CBAQQB+AGBOBKQCIB4CpAiIAsAIQCxAbAUAdQgEAmhuAQIgTAAg");
	this.shape_38.setTransform(-71.5,-86.5);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.lf(["#F71F18","#7A191F"],[0,1],-73.3,0.2,74.9,0.2).s().p("ArYDWIABAAQAjgjCUiiIAWgWIAigkIAagaQBZhaBRg0QBXgZB3AgQA1APA4AUIADABIALAEQDXBTCsAlIAlAIIA1AJIADABIAYAEIAXADIASADQBhAPAeASQAoASgdAPQgVAUh5AQQgeAEgjADQjFAOjlhUIgkgMQjlhJkMCJIg5AeQjQBygSAAQgFAAAGgHg");
	this.shape_39.setTransform(-69.9,-66.3);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.lf(["#F71F18","#7A191F"],[0,1],-77.5,-0.4,78,-0.4).s().p("AIeC+IgCAAIg4gKIgggHIg8gPIgJgCIg9gRIjfhKIgigNIgcgKIglgOIgXgIQi1g5hpApQgnAKiAAxIgiAOIgpAOIgYAKQkWBoBygyQBOgjC7hzQBfg4B6g8QCchPB6ABQCEgGBIBYQB6COCxAnQAWAFAXADQCxAaAbAcQACAmh1AOIgTABIhEABIgdAAg");
	this.shape_40.setTransform(-73,-88);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.lf(["#F71F18","#7A191F"],[0,1],-74.1,0,75.2,0).s().p("ArgD1QAjgnCRiqIAVgZIAhglIAYgcQBXhmBBhKQBVgkB+AdQAqAKAtAOIAlAOIAdALIAiANIDeBKIA+AQIAIADIA9AOIAgAHIA3AKIACAAIALACIAXADIATAEQBcAOAoAQQA1AQgPARQgKAXiEAUQgfAFgjAEQjMAWjohSQgTgGgTgFQjhg+kaCeIg5AhQjSB4gTAAQgEAAAGgGg");
	this.shape_41.setTransform(-70.2,-63.8);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.lf(["#F71F18","#7A191F"],[0,1],-75.2,0,75.2,0).s().p("ArrEUQAjgpCNiyQCKitBHiHIAEgGQB6g/D2BhQD4BhDAAnIA4AKIAbAFQDbAfAAAhQAAAfjTAdQjSAdjshPQjqhNlCDDQkKCjgWAAQgEAAAGgHg");
	this.shape_42.setTransform(-70.2,-61.3);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.lf(["#F71F18","#7A191F"],[0,1],-79.1,0,79.1,0).s().p("AHpDDQjAgnj4hhQj2hfh6A9IgEAHQgeAFjvBXQkhBpCGg4QCFg3FsjSQFqjUB5C6QB4C4DbAgQDbAfAAAhQAAAhjVAKIghABIg4gLg");
	this.shape_43.setTransform(-74.1,-89.7);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.lf(["#F71F18","#7A191F"],[0,1],-77.8,0,77.7,0).s().p("AHaC5Qi/gnj4hhQj3hfiCBBIgKAKQgcAGjDBHQkaBqBzgyQBygyFHjGQFFjJCeCtQCdCqDbAgQDaAfAAAhQAAAhjVAKIghABIg4gLg");
	this.shape_44.setTransform(-72.7,-88.7);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.lf(["#F71F18","#7A191F"],[0,1],-74.6,0.3,74.7,0.3).s().p("ArlD3QAjgnCVitQByiNA9huIAKgKQCChDD3BhQD4BhC/AnIA4ALQD2AjAAAfQAAAhjTAZQjTAZjzhXQjyhWk0CyQj+CVgUAAQgFAAAHgHg");
	this.shape_45.setTransform(-69.7,-64);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.lf(["#F71F18","#7A191F"],[0,1],-76.5,0,76.4,0).s().p("AHMCvQi/gnj4hhQj3hgiLBHIgPALQgaAHiXA3QkTBsBfgsQBfgtEii7QEji+DACgQDCCdDbAfQDaAgAAAhQAAAhjVAJIghABIg4gKg");
	this.shape_46.setTransform(-71.3,-87.7);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.lf(["#F71F18","#7A191F"],[0,1],-74.1,0.6,74.1,0.6).s().p("ArgDbQAkglCdipQBahtAzhWIAPgLQCLhJD4BiQD3BhC/AnIA4AKQD2AiAAAhQAAAhjTAVQjUAVj7hgQj5hfknCiQjxCGgTAAQgEAAAGgGg");
	this.shape_47.setTransform(-69.1,-66.8);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.lf(["#F71F18","#7A191F"],[0,1],-75.2,0,75,0).s().p("AG/ClQjAgnj4hhQj2hgiUBLQgLAHgKAHQgYAHhrAoQkMBtBMgnQBLgnD+iwQD+iyDlCSQDmCQDbAfQDbAgAAAhQAAAhjVAJIghABIg4gKg");
	this.shape_48.setTransform(-69.9,-86.7);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.lf(["#F71F18","#7A191F"],[0,1],-73.5,0.9,73.6,0.9).s().p("AraC+QAkghClijQBChPApg+QAKgIALgGQCUhND4BhQD2BhDAAnIA4AJQD2AjAAAhQAAAhjUASQjUARkDhpQkBhnkYCRQjlB3gSAAQgEAAAGgGg");
	this.shape_49.setTransform(-68.5,-69.5);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.lf(["#F71F18","#7A191F"],[0,1],-73.8,0,73.7,0).s().p("AGyCaQjAgnj2hhQj4hfidBQIgaAQQgWAHhAAYQkEBvA4ghQA4giDZilQDainEJCFQELCCDbAgQDbAfAAAhQAAAhjVAKIghABIg4gLg");
	this.shape_50.setTransform(-68.6,-85.6);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.lf(["#F71F18","#7A191F"],[0,1],-72.9,1.3,73,1.3).s().p("ArUChQAlgeCtifQAqgvAegmIAagQQCdhSD5BiQD2BhC/AlIA4AKQD2AkAAAhQAAAhjUANQjVAOkKhyQkJhvkKB/QjYBpgSAAQgEAAAHgGg");
	this.shape_51.setTransform(-68,-72.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14}]}).to({state:[{t:this.shape_17},{t:this.shape_16}]},1).to({state:[{t:this.shape_19},{t:this.shape_18}]},1).to({state:[{t:this.shape_21},{t:this.shape_20}]},1).to({state:[{t:this.shape_23},{t:this.shape_22}]},1).to({state:[{t:this.shape_25},{t:this.shape_24}]},1).to({state:[{t:this.shape_27},{t:this.shape_26}]},1).to({state:[{t:this.shape_29},{t:this.shape_28}]},1).to({state:[{t:this.shape_31},{t:this.shape_30}]},1).to({state:[{t:this.shape_33},{t:this.shape_32}]},1).to({state:[{t:this.shape_35},{t:this.shape_34}]},1).to({state:[{t:this.shape_37},{t:this.shape_36}]},1).to({state:[{t:this.shape_39},{t:this.shape_38}]},1).to({state:[{t:this.shape_41},{t:this.shape_40}]},1).to({state:[{t:this.shape_43},{t:this.shape_42}]},1).to({state:[{t:this.shape_45},{t:this.shape_44}]},1).to({state:[{t:this.shape_47},{t:this.shape_46}]},1).to({state:[{t:this.shape_49},{t:this.shape_48}]},1).to({state:[{t:this.shape_51},{t:this.shape_50}]},1).to({state:[{t:this.shape_15},{t:this.shape_14}]},1).wait(1));

	// Слой 1
	this.instance_3 = new lib.Символ1();
	this.instance_3.setTransform(27,-47);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(20));

	// Слой 5
	this.instance_4 = new lib.Символ6();
	this.instance_4.setTransform(81,-86.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({rotation:4.4,y:-106.5},4,cjs.Ease.get(-1)).to({rotation:0,y:-86.5},5,cjs.Ease.get(1)).to({rotation:4.4,y:-106.5},5,cjs.Ease.get(-1)).to({rotation:0,y:-86.5},5,cjs.Ease.get(1)).wait(1));

	// Слой 4
	this.instance_5 = new lib.Символ7();
	this.instance_5.setTransform(24.5,-6.4,1,1,0,0,0,47.5,-14.7);

	this.timeline.addTween(cjs.Tween.get(this.instance_5).to({scaleX:1,scaleY:1,rotation:-61.9},4,cjs.Ease.get(-1)).to({regX:47.4,regY:-14.8,scaleX:1,scaleY:1,rotation:-144.3,x:24.4},5,cjs.Ease.get(1)).to({scaleX:1,scaleY:1,rotation:-77,y:-6.5},5,cjs.Ease.get(-1)).to({regX:47.5,regY:-14.7,scaleX:1,scaleY:1,rotation:0,x:24.5,y:-6.4},5,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-139.8,-165.4,366.3,227);


(lib.sprite35 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.shape20("synched",0);
	this.instance.setTransform(28.9,-55.1);

	this.instance_1 = new lib.shape21("synched",0);
	this.instance_1.setTransform(28.9,-55.1);

	this.instance_2 = new lib.shape22("synched",0);
	this.instance_2.setTransform(28.9,-55.1);

	this.instance_3 = new lib.shape23("synched",0);
	this.instance_3.setTransform(28.9,-55.1);

	this.instance_4 = new lib.shape24("synched",0);
	this.instance_4.setTransform(28.9,-55.1);

	this.instance_5 = new lib.shape25("synched",0);
	this.instance_5.setTransform(28.9,-55.1);

	this.instance_6 = new lib.shape26("synched",0);
	this.instance_6.setTransform(28.9,-55.1);

	this.instance_7 = new lib.shape27("synched",0);
	this.instance_7.setTransform(28.9,-55.1);

	this.instance_8 = new lib.shape28("synched",0);
	this.instance_8.setTransform(28.9,-55.1);

	this.instance_9 = new lib.shape29("synched",0);
	this.instance_9.setTransform(28.9,-55.1);

	this.instance_10 = new lib.shape30("synched",0);
	this.instance_10.setTransform(28.9,-55.1);

	this.instance_11 = new lib.shape31("synched",0);
	this.instance_11.setTransform(28.9,-55.1);

	this.instance_12 = new lib.shape32("synched",0);
	this.instance_12.setTransform(28.9,-55.1);

	this.instance_13 = new lib.shape33("synched",0);
	this.instance_13.setTransform(28.9,-55.1);

	this.instance_14 = new lib.shape34("synched",0);
	this.instance_14.setTransform(28.9,-55.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.instance_1}]},1).to({state:[{t:this.instance_2}]},1).to({state:[{t:this.instance_3}]},2).to({state:[{t:this.instance_4}]},1).to({state:[{t:this.instance_5}]},2).to({state:[{t:this.instance_6}]},2).to({state:[{t:this.instance_7}]},1).to({state:[{t:this.instance_8}]},2).to({state:[{t:this.instance_9}]},2).to({state:[{t:this.instance_10}]},1).to({state:[{t:this.instance_11}]},2).to({state:[{t:this.instance_12}]},1).to({state:[{t:this.instance_13}]},2).to({state:[{t:this.instance_14}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-43.4,-21.5,88.5,60.1);


(lib.Символ30 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ28();
	this.instance.setTransform(-0.1,-0.1,1,1,0,0,0,-0.2,0);
	this.instance.alpha = 0.672;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({scaleX:0.84,scaleY:0.84,alpha:0.84},7,cjs.Ease.get(-1)).to({scaleX:0.67,scaleY:0.67,x:-0.2,alpha:1},7,cjs.Ease.get(1)).to({scaleX:0.83,scaleY:0.83,x:-0.1,y:-0.2,alpha:0.852},7,cjs.Ease.get(-1)).to({scaleX:1,scaleY:1,y:-0.1,alpha:0.672},8,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-51.3,-51.2,102,103);


(lib.Символ26 = function() {
	this.initialize();

	// Слой 2
	this.instance = new lib.sprite35();
	this.instance.setTransform(-49,-1.4,0.18,0.18,-93.3);
	this.instance.alpha = 0.398;
	this.instance.compositeOperation = "lighter";

	// Слой 1
	this.instance_1 = new lib.bow();
	this.instance_1.setTransform(-45.8,-118.2);

	this.addChild(this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-53.3,-118.2,99.6,237);


(lib.Символ8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ2();
	this.instance.setTransform(-43.3,52);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({y:97},4,cjs.Ease.get(-1)).to({y:68.2},2,cjs.Ease.get(1)).to({y:52},3).to({y:97},5,cjs.Ease.get(-1)).to({y:52},5,cjs.Ease.get(1)).wait(1));

	// Слой 3 - копия
	this.instance_1 = new lib.sprite27копия();
	this.instance_1.setTransform(42.2,117.3,0.407,0.407,0,0,180);
	this.instance_1.alpha = 0.398;

	this.instance_2 = new lib.sprite27();
	this.instance_2.setTransform(42.2,117.3,0.407,0.407,0,0,180);
	this.instance_2.alpha = 0.398;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_1}]}).to({state:[]},8).to({state:[{t:this.instance_2}]},6).wait(6));

	// Слой 3
	this.instance_3 = new lib.sprite27();
	this.instance_3.setTransform(37.9,124.1,0.407,0.407,0,0,180);
	this.instance_3.alpha = 0.398;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(6).to({_off:false},0).wait(14));

	// Слой 2
	this.instance_4 = new lib.Символ10();
	this.instance_4.setTransform(-14.8,156.5,0.694,1);

	this.timeline.addTween(cjs.Tween.get(this.instance_4).to({scaleX:1},4,cjs.Ease.get(-1)).to({scaleX:0.69},5,cjs.Ease.get(1)).to({scaleX:1},5,cjs.Ease.get(-1)).to({scaleX:0.69},5,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-183.1,-113.5,366.3,308.2);


(lib.Символ34 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_1 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(1));

	// Слой 1
	this.instance = new lib.Символ30();
	this.instance.setTransform(-0.2,0,1,1,0,0,0,-0.2,0);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Символ32 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ26();
	this.instance.setTransform(-0.1,3.7,1,1,90.4,0,0,-0.1,0.1);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({rotation:90.3,y:9.2},5,cjs.Ease.get(-1)).to({rotation:90.4,y:15.7},6,cjs.Ease.get(1)).to({rotation:90.3,x:0,y:10.2},6,cjs.Ease.get(-1)).to({rotation:90.4,x:-0.1,y:3.7},7,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-119.1,-49.5,237.7,100.4);


(lib.Символ9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Символ8();
	this.instance.setTransform(-40.4,0,1,1,0,0,0,-6.7,0);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:351.3},99).to({x:-40.4},100).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-216.8,-113.5,366.3,308.2);


(lib.Символ35 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_1 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(1));

	// Слой 1
	this.instance = new lib.Символ32();
	this.instance.setTransform(-2.5,-1.6,1,1,-58.3,0,0,0,-3);

	this.timeline.addTween(cjs.Tween.get(this.instance).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-98.7,-122.4,204,249.6);


(lib.Символ33 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_1 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(1));

	// Слой 1
	this.instance = new lib.Символ32();
	this.instance.setTransform(120,-43,1,1,-58.3,0,0,0,-3);
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.Символ12 = function() {
	this.initialize();

	// Слой 3
	this.instance = new lib.Символ37();
	this.instance.setTransform(-133,128.2);

	// Слой 4
	this.instance_1 = new lib.counter();
	this.instance_1.setTransform(-181.8,94.7);

	// Слой 1
	this.instance_2 = new lib.Символ9();
	this.instance_2.setTransform(20.9,-7.3,0.771,0.771,0,0,0,-6.7,0);

	// Слой 5
	this.instance_3 = new lib.Символ39();
	this.instance_3.setTransform(140.1,-112.3);

	// Слой 2
	this.instance_4 = new lib.ground();
	this.instance_4.setTransform(-180.8,82.2);

	// Режим изоляции
	this.instance_5 = new lib.Символ20();
	this.instance_5.setTransform(141.7,46.6,1,1,0,0,0,1,0.1);

	// Слой 10
	this.instance_6 = new lib.Символ23();
	this.instance_6.setTransform(312.2,17.2);

	// Слой 9
	this.instance_7 = new lib.sky();
	this.instance_7.setTransform(-180.7,-145.8);

	this.addChild(this.instance_7,this.instance_6,this.instance_5,this.instance_4,this.instance_3,this.instance_2,this.instance_1,this.instance);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-181.8,-145.8,1912,318);


// stage content:
(lib.spartan = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		var _this = this;
		
		stage.canvas.onmouseover = fl_MouseOverHandler_5;
		
		 function fl_MouseOverHandler_5()
		{
		    _this.pricel2.gotoAndPlay(1);
			_this.bow.gotoAndPlay(1);
			_this.luk.gotoAndPlay(1);
		}
		
		stage.canvas.onmouseout = fl_MouseOutHandler_2;
		
		 function fl_MouseOutHandler_2()
		{
		    _this.pricel2.gotoAndPlay(0);
			_this.bow.gotoAndPlay(0);
			_this.luk.gotoAndPlay(0);
		}
		
		
		stage.canvas.style.cursor = "none";
		this.bow.mouseEnabled = false;
		this.addEventListener("tick", fl_CustomMouseCursor.bind(this));
		
		function fl_CustomMouseCursor() {
			this.bow.x = stage.mouseX;
		}
		
		
		
		
		stage.canvas.style.cursor = "none";
		this.pricel2.mouseEnabled = false;
		this.addEventListener("tick", fl_CustomMouseCursor_2.bind(this));
		
		function fl_CustomMouseCursor_2() {
			this.pricel2.x = stage.mouseX;
			this.pricel2.y = stage.mouseY;
		}
		//Чтобы восстановить курсор мыши по умолчанию, раскомментируйте следующие строки:
		//this.removeEventListener("tick", fl_CustomMouseCursor_2.bind(this));
		//stage.removeChild(pricel2);
		//stage.canvas.style.cursor = "default";
		
		
		
		this.main.addEventListener("click", fl_ClickToGoToWebPage);
		
		function fl_ClickToGoToWebPage() {
			window.open(clickTAG, "_blank");
		}
		var bodyStyle = document.body.style;
		bodyStyle.margin = 0;
		bodyStyle.padding = 0;
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Режим изоляции
	this.pricel2 = new lib.Символ34();
	this.pricel2.setTransform(171.5,128.1);

	this.timeline.addTween(cjs.Tween.get(this.pricel2).wait(1));

	// Слой 6
	this.bow = new lib.Символ33();
	this.bow.setTransform(311.8,278.6,1,1,0,0,0,-0.1,-3.1);

	this.timeline.addTween(cjs.Tween.get(this.bow).wait(1));

	// Слой 2
	this.luk = new lib.Символ35();
	this.luk.setTransform(506.5,262.4,1,1,0,0,0,-2.6,-1.6);

	this.timeline.addTween(cjs.Tween.get(this.luk).wait(1));

	// Слой 1
	this.main = new lib.Символ12();
	this.main.setTransform(175.6,145.9,1,1,0,0,0,-5.2,0);

	this.timeline.addTween(cjs.Tween.get(this.main).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(319,152.5,1912,391.1);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;